### PR TITLE
Remove duplicate function uss_tag_encoding from encode utils

### PR DESCRIPTION
**Pull request by fernandofloresg**
##### SUMMARY

There is a duplicated function in line 456 and line 499 `uss_tag_encoding`

##### ISSUE TYPE

- Trivial Pull Request

##### COMPONENT NAME

module_utils/encode.py

##### ADDITIONAL INFORMATION

The linter somehow doesn't seem to complain about the fact that there are two functions with the same name.

```paste below

```

### CODE REVIEW

**Comment by fernandofloresg** [comment]
Will this need a changelog? I don't think so, is so trivial. But we do have a trivial tag too. I guess since it doesn't change any behavior wouldn't need.

**Review by ddimatos — APPROVED** [review]
@fernandofloresg good catch, saved us a pipeline failure, guessing auto-merge introduced this.

**Comment by fernandofloresg** [comment]
Screenshot 2023-04-24 at 4 02 44 PM

Thanks for approving @ddimatos here is the pipeline execution.

**Review by rexemin — APPROVED** [review]
Thanks for catching this!

**Review by ketankelkar — APPROVED** [review]
lgtm

**Pull request merged**
