### PR TITLE
updated copyright and fixed minor issues

### PR DESCRIPTION
**Pull request by RadhaV2020**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by richp405 — APPROVED** [review]
Good changes on those typos.  Thank you.  My only concern is all the doc files... I don't know if this is the right place to change them.

**Comment by RadhaV2020** [comment]
> Good changes on those typos. Thank you. My only concern is all the doc files... I don't know if this is the right place to change them.

That was my doubt about the other files as well, @richp405 Rich. I will check with Demetri.

**Comment by ddimatos** [comment]
@richp405  was correct on questioning this commit.

@RadhaV2020 - the changes for module zos_copy should be done in a separate commit, by mixing in all these other changes into one commit, if I should ever need to back out or backport I get a bunch of other changes unrelated to zos_copy module which are difficult to manage. Given these are simple copyright year changes, its not that difficult to wade through. The practice that should be followed is that you changes should have been made to zos_copy, `git add zos_copy.py` , `git commit  - s -m ".... what i changed"; `git push` , then changes to the coyright years, `git add .` ; `git commit  - s -m ".... what i changed"; `git push`.

On to the copyright, it seems like many of the copyright yrs were edited without change happening in that source file. Copyright years should be added when a change happens in the file, we usually catch that during any review, at this point leave it and I will handle them, in the future, if you edit a file change the copyright year, if its generated RST like under the modules folder I will have sphinx make the change during generation (done during a release), if its static RST  and you change it change the copyright year.

**Comment by ddimatos** [comment]
I did the commits over to avoid pulling unrelated changes to the zos_copy module and also removed the below files because they show no changes in 2021 to warrant a copyright update. 
```
docs/source/filters.rst
docs/source/installation.rst
docs/source/license.rst
docs/source/plugins.rst
```

**Review by ddimatos — APPROVED** [review]

**Pull request merged**
