### PR TITLE
[v1.10.0] [zos_data_set] ZOAU 1.3 migration - zos_data_set

### LINKED ISSUE #1124: [Enabler] [tests/test_zos_data_set_func.py] Migrate module, module utilities and test cases to ZOAU 1.3
## module_utils
`test_zos_data_set_func.py`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

With the adoption of ZOAU 1.3, modules, module utilities and test cases may need to be updated according to the [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier). 

APIs changes affecting module:
- Impacted by ZOAU Dataset API: No
- Impacted by ZOAU jobs API: No
- Impacted by the rename of types.py to ztypes.py: No
- Impacted by the contents of module volumes.py having been moved to datasets.py: No
- Impacted by opercmd timeout to milli seconds: No
- Impacted by JSON schema change: Yes (zinfo)
- Impacted by Exceptions schema: No

Review the [zoautil_py datasets module migration doc](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier#changes-to-the-datasets-module).

Upon review, this module is affected by:
- the utilities apfadm, dmod, dsed, and zinfo supported limited JSON output with a schema that is now obsolete, so any use of previous output must be updated
   - See `result0 = hosts.all.shell(cmd="zinfo -t sys")`

- Note, that the content for `zinfo` has been encapsulated with a `data` object (#954), validation should be covered through regression testing to ensure our formatting is correct and possibly we might need to extract the content from the data object or create a migration guide. 

For reference the JSON Schema changes with examples should also be reviewed:
https://www.ibm.com/docs/en/zoau/1.3.x?topic=examples-json-schema

#954 - we may cancel this issue if the work is handled on each module

To learn more, see [ZOAU JSON schema and examples](https://www.ibm.com/docs/en/SSKFYE_1.3.x/json_examples.html).

This issue depends on shared import identified by git issues:
- [module_utils/better_arg_parser.py](https://github.com/ansible-collections/ibm_zos_core/issues/1116)

### LINKED ISSUE #1145: [Enabler] [Val] [zos_data_set] Validate module with ZOAU 1.3
## Ansible Module
`zos_data_set`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

This module has no identified migration work, its test cases have minimal to no module dependencies and because it is a foundational module used by other test cases need to have regression run. This modules regression should only be run, running other regression will result in error, on success, this issue can be closed.
 
[Migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier) for reference.

### LINKED ISSUE #1240: [Bug] [module_utils/data_set] Helper function `data_set_cataloged_volume_list` leaves leading '-' in list of volume serials it parses out from a LISTCAT command
The `data_set_cataloged_volume_list` function in `module_utils/data_set.py` contains a tiny bug with the regex/processing where the captured `volser` strings are **always** 6 chars long -- and if the `volser` isn’t 6 chars, then a `'-'` is pre-prended. eg:
```['222222', '-SCR03', '000000']```

This list of strings gets compared to the user-input list of strings, which results in a mismatch and causes the caller to report the data set as NOT present on the target data set. The rest of the module logic operates based on this false assumption, which leads to unpredictable behaviors. 

Note - this behavior only poses an issue when a volume serial is under 6 chars (eg `SCR03`). 

The test case which surfaced this issue was `test_data_set_replacement_when_uncataloged`

### LINKED ISSUE #1241: [Bug] [zos_data_set] Handle erroneous DatasetVerificationError for data set spanning across multiple volumes
When creating a non-VSAM data set spanning multiple volumes, a `DatasetCreationError` is raised by the `zos_data_set` modules because in the process of creating the data set, it receives a `DatasetVerificationError` from the call to `datasets.create()` due to a bug in the `datasets.list_datasets()` function which is only used to validate the data set creation. The mutli-volume data set is indeed successfully created, only it is reported as the opposite.

The failing test case during the course of the migration which led to the discovery of this bug was `test_multi_volume_creation_uncatalog_and_catalog_nonvsam`.

playbook task:
```yaml
  - name: create ONE data set across multiple volumes
    tags: multivol
    block:
    - name: create data set on 2 vols
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ DEFAULT_DATA_SET_NAME }}"
        type: "SEQ"
        space_primary: 5
        space_type: "CYL"
        record_length: 15
        state: present
        volumes: ['000000', '222222']
```
result (edited for privacy and readability):
```
TASK [create data set on 2 vols] ***************************************************************************************************************************************************************************************************************************************************
Monday 19 February 2024  15:06:11 -0800 (0:00:00.007)       0:00:00.007 ******* 
fatal: [zvm]: FAILED! => {
    "changed": false,
    "message": "",
    "msg": 
        "DatasetCreateError('An error occurred during creation of data set
            \"USER.PRIVATE.TESTDS\". RC=-1, DatasetVerificationError received from ZOAU...')",
        "names": ["USER.PRIVATE.TESTDS"]
}
```

Where the error message is created by temporary code placed in the `module_utils/data_set.py:::DataSet.create()` function to handle the newly introduced (ZOAU v1.3.0) DatasetVerificationError.

The above `DatasetVerificationError` comes from a call to ZOAU python API `datasets.create()`. That function creates the data set, and as a final step for the purposes of validation, calls `datasets.list_datasets()`, which fails and causes the `datasets.create()` function to raise the `DatasetVerificationError`. 

The `datasets.list_datasets()` function calls the command-line `dls` under the covers. The `datasets.list_datasets()` function seems to throw an error when it gets unclean/unexpected output from `dls`. 
For a call to `dls` against a data set spanning multiple volumes, there is the usual `dls` output *and* an information message.

result of dls:
```
OMVSADM.PRIVATE.TESTDS                       PS  FB      15 000000            0      4249800
BGYSC2006I Unable to obtain dataset information for dataset OMVSADM.PRIVATE.TESTDS on volume 222222. 
``` 

recreate of datasets.list_dataset():
- python script:
```python3
import os, traceback
from zoautil_py import datasets

dsn = 'somehlq.private.testds'.upper()

datasets.delete(dsn)

print('#############################')
print("# Attempt datasets.create() #")
print('#############################\n')

# the following call FAILS BUT creates the data set
try:
    datasets.create(name=dsn, dataset_type='SEQ', primary_space='5CYL', secondary_space='3CYL', record_format='FB', record_length=15, volumes="000000,222222")
except Exception:
    traceback.print_exc()

print("\n#######", "\n# end #","\n#######\n")
```
- result:
```
############################
# Attempt datasets.create() #
#############################

Traceback (most recent call last):
  File "/zoau/v1.3.0/lib/3.11/zoautil_py/datasets.py", line 698, in create
    dataset = list_datasets(name)[0]
              ^^^^^^^^^^^^^^^^^^^
  File "/zoau/v1.3.0/lib/3.11/zoautil_py/datasets.py", line 1216, in list_datasets
    response_json, _ = zoau_json_load(response.stdout_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zoau/v1.3.0/lib/3.11/zoautil_py/common.py", line 190, in zoau_json_load
    raise js_ex
  File "/zoau/v1.3.0/lib/3.11/zoautil_py/common.py", line 187, in zoau_json_load
    root_json = json.loads(json_text)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/allpython/3.11/usr/lpp/IBM/cyp/v3r11/pyz/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/allpython/3.11/usr/lpp/IBM/cyp/v3r11/pyz/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/allpython/3.11/usr/lpp/IBM/cyp/v3r11/pyz/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/omvsadm/hi.py", line 15, in <module>
    datasets.create(name=dsn, dataset_type='SEQ', primary_space='5CYL', secondary_space='3CYL', record_format='FB', record_length=15, volumes="000000,222222")
  File "/zoau/v1.3.0/lib/3.11/zoautil_py/datasets.py", line 700, in create
    raise DatasetVerificationError(name)
zoautil_py.exceptions.DatasetVerificationError: SOMEHLQ.PRIVATE.TESTDS

####### 
# end # 
#######
```

Note- the issue with `datasets.list_datasets()` has been reported to the ZOAU team and is tracked in the internal JIRA-10432

### PR DESCRIPTION
**Pull request by ketankelkar**
##### SUMMARY

Migration work for `ibm.ibm_zos_core.zos_data_set` Ansible module and corresponding test suite.
Two bugs were uncovered over the course of the migration, which were related to the migration and hence addressed within this very same PR.

- Fixes #1145 
- Fixes #1124 
- Fixes #1240 
- Fixes #1241 
##### ISSUE TYPE

- Enabler Pull Request (regarding migration work)
- Bugfix Pull Request (2 bugs were uncovered and addressed in the code changes)

##### COMPONENT NAME

migrate to ZOAU v1.3.0:
- zos_data_set - ibm.ibm_zos_core Ansible module
- test_zos_data_set_func  - functional test suite for above module

##### ADDITIONAL INFORMATION
- #1240 
  - a hidden parsed string processing error was uncovered where leading `-` char(s) would be left behind when parsing any volume serials less than 6 chars from the contents of a LISTCAT command. This behavior led to some unpredictable behaviors around cataloged and uncataloged data sets. This bug was uncovered by the `test_data_set_absent_when_uncataloged`functional test.
- In previous versions, the error from DYNALLOC would be passed to the module where if a specific error code `0x4704` (`Duplicate data set name on the volume identified by message IKJ56229I. (program error)`) was detected, the module would attempt to catalog the data set. With the current implementation, that error code is no longer passed up to the module via the `DatasetVerificationError`. The condition check has been broadened to accept `DatasetVerificationError` and let the existing error handling within that logic handle unnecessary attempts to catalog a data set. I believe the trade-off here is between a potential for extra/unnecessary calls to the `catalog_if_necessary()` function but having the existing subsequent error handling process the catalog attempt versus re-probing the z/OS system in an attempt to get the expected error code and then carrying on with the logic to catalog a data set if necessary.
  - ```python3
       if not present:
            try:
                DataSet.create(**arguments)
            except DatasetCreateError as e:
                raise_error = True
                # data set exists on volume
     ---->  if "DatasetVerificationError" in e.msg or "Error Code: 0x4704" in e.msg:   <--- THIS broadened conditional
                    present, changed = DataSet.attempt_catalog_if_necessary(
                        name, volumes
                    )
        ---->   if present and changed:   <---- THIS logic here makes broadening the coniditional safe
                        raise_error = False
                if raise_error:
                    raise```
  - The conditional statement `if present and changed` ensures that the target data set was indeed catalog-ed (and of course exists). If it does not exist, or if it was already 'cataloged' and the `attempt_catalog_if_necessary` took no action (i.e. returned `changed=False`), then the DatasetCreateError which flowed to this code path was indeed erroneous and an Exception is raised.
- #1241 
  - This one relates closely to the ZOAU v1.3.0 migration work because the newer version of ZOAU introduced a new suite of Errors including one `DatasetVerificationError`. The ZOAU python API function `datasets.create()` leverages the `datasets.list_datasets()` function to validate the created data set and throws a `DatasetVerificationError` if that `list_datasets()` call has an unexpected return. In the case of a data set spanning multiple volumes, that function throws a JSONDecodeError, which causes `datasets.create()` to throw a `DatasetVerificationError` which causes the Ansible module_util's `DataSet.create()` function to throw a `DatasetCreateError`. However, the creation of the data set has indeed been successful. And thus as a temporary work-around while the JSONDecodError thrown by the `datasets.list_datasets()`, the `ibm.ibm_zos_core.zos_data_set` module does its own verification for instance where the number of volumes is more than 1.
  - ```python3
          except exceptions.DatasetVerificationError as e:
            # verification of a data set spanning multiple volumes is currently broken in ZOAU v.1.3.0
            if len(volumes) > 1:
                if DataSet.data_set_cataloged(name, volumes):
                    return 0
            raise DatasetCreateError(
                name,
                rc=-1,
                msg="DatasetVerificationError received from ZOAU...",
            )
        # With ZOAU 1.3 we switched from getting a ZOAUResponse obj to a Dataset obj, previously we returned
        # response.rc now we just return 0 if nothing failed
        return 0

### CODE REVIEW

**Comment by ketankelkar** [comment]
image

image

image

**Review by AndreMarcel99 — APPROVED** [review]

**Comment by ketankelkar** [comment]
I converted this PR back to draft because I remembered I still have to change the error message raised by `module_utils/data_set.py::create()`:
```
msg="DatasetVerificationError received from ZOAU...",
```

**Comment by ketankelkar** [comment]
Re-converted to draft, I have an idea to change the message structure of the `DatasetCreateError` to avoid a hard-coded return code completely made up by me for the purposes of providing an "rc".
```python
    raise DatasetCreateError(
                name,
  ----->     rc=-1,
                msg="Unable to verify the data set was created. Received DatasetVerificationError from ZOAU.",
            )
```

The idea is to change the following definition:
```python3
class DatasetCreateError(Exception):
    def __init__(self, data_set, rc, msg=""):
        self.msg = (
            'An error occurred during creation of data set "{0}". RC={1}, {2}'.format(
                data_set, rc, msg
            )
        )
        super().__init__(self.msg)
```
Since the a DatasetCreateError is only a message (str), there is space to modify the str to include or not include an RC. In the above case, it makes sense to excude the RC, so a conditional statement can be introduced in this definition to optionally return an error message without the RC. Better to not return an RC than to return a made up RC

In playbook output (formatted for readability):
```
fatal: [zvm]: FAILED! => {
    "changed": false,
    "message": "", 
    "msg":
        "DatasetCreateError(
            'An error occurred during creation of data set \"KETAN.PRIVATE.TESTDS\". 
             Unable to verify the data set was created. Received DatasetVerificationError from ZOAU.'
        )",
    "names": ["KETAN.PRIVATE.TESTDS"]}
```

**Comment by ketankelkar** [comment]
```
python3 -m pytest -v -x -rf --host-pattern=all --zinventory=tests/test_config.yml tests/functional/modules/test_zos_data_set_func.py
```


```
================= 69 passed, 74 warnings in 968.45s (0:16:08) ==================
```

image

image


```
============================= test session starts ==============================
platform linux -- Python 3.9.17, pytest-7.4.2, pluggy-1.3.0 -- /usr/local/bin/python3
cachedir: .pytest_cache
ansible: 2.15.5
rootdir: /var/lib/jenkins/workspace/zosAnsible-Ketan/ibm_zos_core/tests
configfile: pytest.ini
plugins: mock-3.12.0, ansible-4.1.1
collecting ... collected 69 items

tests/functional/modules/test_zos_data_set_func.py::test_data_set_catalog_and_uncatalog[PDS_CREATE_JCL] PASSED [  1%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_catalog_and_uncatalog[KSDS_CREATE_JCL] PASSED [  2%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_catalog_and_uncatalog[RRDS_CREATE_JCL] PASSED [  4%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_catalog_and_uncatalog[ESDS_CREATE_JCL] PASSED [  5%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_catalog_and_uncatalog[LDS_CREATE_JCL] PASSED [  7%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_present_when_uncataloged[PDS_CREATE_JCL] PASSED [  8%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_present_when_uncataloged[KSDS_CREATE_JCL] PASSED [ 10%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_present_when_uncataloged[RRDS_CREATE_JCL] PASSED [ 11%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_present_when_uncataloged[ESDS_CREATE_JCL] PASSED [ 13%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_present_when_uncataloged[LDS_CREATE_JCL] PASSED [ 14%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_replacement_when_uncataloged[PDS_CREATE_JCL] PASSED [ 15%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_replacement_when_uncataloged[KSDS_CREATE_JCL] PASSED [ 17%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_replacement_when_uncataloged[RRDS_CREATE_JCL] PASSED [ 18%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_replacement_when_uncataloged[ESDS_CREATE_JCL] PASSED [ 20%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_replacement_when_uncataloged[LDS_CREATE_JCL] PASSED [ 21%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_absent_when_uncataloged[PDS_CREATE_JCL] PASSED [ 23%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_absent_when_uncataloged[KSDS_CREATE_JCL] PASSED [ 24%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_absent_when_uncataloged[RRDS_CREATE_JCL] PASSED [ 26%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_absent_when_uncataloged[ESDS_CREATE_JCL] PASSED [ 27%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_absent_when_uncataloged[LDS_CREATE_JCL] PASSED [ 28%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_absent_when_uncataloged_and_same_name_cataloged_is_present[PDS_CREATE_JCL] PASSED [ 30%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_absent_when_uncataloged_and_same_name_cataloged_is_present[KSDS_CREATE_JCL] PASSED [ 31%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_absent_when_uncataloged_and_same_name_cataloged_is_present[RRDS_CREATE_JCL] PASSED [ 33%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_absent_when_uncataloged_and_same_name_cataloged_is_present[ESDS_CREATE_JCL] PASSED [ 34%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_absent_when_uncataloged_and_same_name_cataloged_is_present[LDS_CREATE_JCL] PASSED [ 36%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_no_replace[pds] PASSED [ 37%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_no_replace[seq] PASSED [ 39%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_no_replace[pdse] PASSED [ 40%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_no_replace[esds] PASSED [ 42%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_no_replace[rrds] PASSED [ 43%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_no_replace[lds] PASSED [ 44%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_replace[pds] PASSED [ 46%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_replace[seq] PASSED [ 47%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_replace[pdse] PASSED [ 49%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_replace[esds] PASSED [ 50%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_replace[rrds] PASSED [ 52%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_present_replace[lds] PASSED [ 53%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_absent[pds] PASSED [ 55%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_absent[seq] PASSED [ 56%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_absent[pdse] PASSED [ 57%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_absent[esds] PASSED [ 59%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_absent[rrds] PASSED [ 60%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_when_absent[lds] PASSED [ 62%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_deletion_when_present[pds] PASSED [ 63%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_deletion_when_present[seq] PASSED [ 65%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_deletion_when_present[pdse] PASSED [ 66%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_deletion_when_present[esds] PASSED [ 68%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_deletion_when_present[rrds] PASSED [ 69%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_deletion_when_present[lds] PASSED [ 71%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_deletion_when_absent PASSED [ 72%]
tests/functional/modules/test_zos_data_set_func.py::test_batch_data_set_creation_and_deletion PASSED [ 73%]
tests/functional/modules/test_zos_data_set_func.py::test_batch_data_set_and_member_creation PASSED [ 75%]
tests/functional/modules/test_zos_data_set_func.py::test_data_member_force_delete PASSED [ 76%]
tests/functional/modules/test_zos_data_set_func.py::test_repeated_operations PASSED [ 78%]
tests/functional/modules/test_zos_data_set_func.py::test_multi_volume_creation_uncatalog_and_catalog_nonvsam PASSED [ 79%]
tests/functional/modules/test_zos_data_set_func.py::test_multi_volume_creation_uncatalog_and_catalog_vsam PASSED [ 81%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_old_aliases PASSED [ 82%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_temp_data_set_name PASSED [ 84%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_temp_data_set_name_batch PASSED [ 85%]
tests/functional/modules/test_zos_data_set_func.py::test_filesystem_create_and_mount[HFS] PASSED [ 86%]
tests/functional/modules/test_zos_data_set_func.py::test_filesystem_create_and_mount[ZFS] PASSED [ 88%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_zero_values PASSED [ 89%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_creation_with_tmp_hlq PASSED [ 91%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_f_formats[F] PASSED [ 92%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_f_formats[FB] PASSED [ 94%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_f_formats[VB] PASSED [ 95%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_f_formats[FBA] PASSED [ 97%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_f_formats[VBA] PASSED [ 98%]
tests/functional/modules/test_zos_data_set_func.py::test_data_set_f_formats[U] PASSED [100%]
```

**Review by fernandofloresg — APPROVED** [review]
Looks good from here. Nice that you added how to handle DatasetVerificationError to our own already inlace exception DatasetCreateError.

**Review by rexemin — APPROVED** [review]

**Pull request merged**
