### PR TITLE
adding requirements file

### PR DESCRIPTION
**Pull request by thedoubl3j**
##### SUMMARY

This PR is a follow up to an email sent to the maintainers of this certified collection notifying them of a few new changes that will be needed for the next Ansible Automation Platform release. Contained in this PR is an example python requirements file built specifically for your collection. You can elect to merge this as is and edit as needed or close the PR and use it as an example to base your own commit off of. If you have any questions about why this PR was sent or confused about its necessity, please don't hesitate to ask in the comments here or email us at ansiblepartners@redhat.com.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

adding requirements file for 
##### ADDITIONAL INFORMATION

some packages were excluded from this file as they are already packaged in ansible or one of its tools that it is packaged with ex: pytest is packaged with ansible-test. 

```paste below
N/A
```

### CODE REVIEW

**Comment by anshulbehl** [comment]
@ddimatos Can you please review this one and do a new release on Ansible Automation Hub?

**Comment by ddimatos** [comment]
Hey @thedoubl3j - I sent you an email with a number of questions about execution environments and its requirements, I want to understand those before going forward with this PR. 

One additional question that is related to this PR. I noticed you have dependencies in the requirements.txt here that are from our test cases. None of our modules are using any of these dependencies, our modules only use what come with the python standard library, given we don't include our test cases in the collection, they are excluded, do we still need to have the entries in requirements.txt?

**Comment by thedoubl3j** [comment]
that is correct @ddimatos they wouldn't be needed, these files were automated in their creation so if the requirements are only needed for testing purposes, they can be dropped.

**Comment by ddimatos** [comment]
@thedoubl3j , fyi, I am closing this as I have pushed https://github.com/ansible-collections/ibm_zos_core/pull/268/files

**Pull request closed without merging**
