### PR TITLE
Bugfix/717/uss tag encoding

### LINKED ISSUE #717: [Bug] zos_encode failing because of missing function uss_tag_encoding
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.2

### IBM Enterprise Python

v3.9.x

### IBM z/OS Ansible core Version

v1.5.0

### ansible-version

latest

### z/OS version

None

### Ansible module

_No response_

### Bug description

Function uss_tag_encoding was added on https://github.com/ansible-collections/ibm_zos_core/commit/5ba30a8badd95fe13f6f12e19371c4f849f8d2fa but somehow is not there anymore, this is breaking the test cases for zos_encode.

### Test suite output 
```
functional/modules/test_zos_encode_func.py ..F

=================================== FAILURES ===================================
__________________ test_uss_encoding_conversion_without_dest ___________________

ansible_zos_module = <pytest_ansible.host_manager.v28.HostManagerV28 object at 0x7f50db246eb0>

    def test_uss_encoding_conversion_without_dest(ansible_zos_module):
        try:
            hosts = ansible_zos_module
            hosts.all.copy(content=TEST_DATA, dest=USS_FILE)
            results = hosts.all.zos_encode(
                src=USS_FILE,
                encoding={
                    "from": FROM_ENCODING,
                    "to": TO_ENCODING,
                },
            )
            pprint(vars(results))
            for result in results.contacted.values():
                assert result.get("src") == USS_FILE
                assert result.get("dest") == USS_FILE
                assert result.get("backup_name") is None
>               assert result.get("changed") is True
E               AssertionError: assert False is True
E                +  where False = <built-in method get of dict object at 0x7f50dadbb300>('changed')
E                +    where <built-in method get of dict object at 0x7f50dadbb300> = {'_ansible_no_log': False, 'changed': False, 'dest': '/tmp/encode.data', 'failed': True, ...}.get

functional/modules/test_zos_encode_func.py:129: AssertionError
----------------------------- Captured stdout call -----------------------------
{'contacted': {'ec33012a.vmec.svl.ibm.com': {'_ansible_no_log': False,
                                             'changed': False,
                                             'dest': '/tmp/encode.data',
                                             'failed': True,
                                             'gid': 1,
                                             'group': 'OMVSGRP',
                                             'invocation': {'module_args': {'backup': False,
                                                                            'backup_compress': False,
                                                                            'backup_name': None,
                                                                            'dest': None,
                                                                            'encoding': {'from': 'IBM-1047',
                                                                                         'to': 'ISO8859-1'},
                                                                            'from_encoding': 'IBM-1047',
                                                                            'src': '/tmp/encode.data',
                                                                            'tmp_hlq': None,
                                                                            'to_encoding': 'ISO8859-1'}},
                                             'mode': '0644',
                                             'msg': 'AttributeError("\'EncodeUtils\' '
                                                    'object has no attribute '
                                                    '\'uss_tag_encoding\'")',
                                             'owner': 'OBAGAOI',
                                             'size': 480,
                                             'src': '/tmp/encode.data',
                                             'state': 'file',
                                             'uid': 0}}}
```

### Playbook verbosity output.

_No response_

### Ansible configuration.

_No response_

### Contents of the inventory

_No response_

### Contents of `group_vars` or `host_vars`

_No response_

### PR DESCRIPTION
**Pull request by fernandofloresg**
##### SUMMARY

Added a missing function which was called in zos_encode encode utils. Apparently it was removed somewhere in between this two commits:

https://github.com/ansible-collections/ibm_zos_core/commit/7fcd62a7b5f9cb2de0447f89c70c830a4dd8ee0b

https://github.com/ansible-collections/ibm_zos_core/commit/98315a49d6ec631ba53eb9414087fa67046507a6

I don't have any idea why. Strangely, similar code snippets added in the merge were present but this function was not. We discovered this recently while modifying zos_copy code based off of dev branch.

Fixes #717 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

zos_encode

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by fernandofloresg** [comment]
Screenshot 2023-03-31 at 2 38 41 PM
Screenshot 2023-03-31 at 2 39 01 PM

**Comment by ddimatos** [comment]
Looks ok to me, ill see if i can figure out why it was removed, it might take some time but to avoid hold back the team, I am approving this, I am familiar with that code but I would like @rexemin to look at it as he recently had gotten feedback and make changes, i just want to be sure these are the changes the he wanted to persist.

**Review by ddimatos — APPROVED** [review]
Thank you.

**Review by rexemin — APPROVED** [review]
Looks good to me. Thank you again @fernandofloresg and @AndreMarcel99 for catching this.

IIRC I took this function from a module (maybe zos_copy) and put it into `module_utils/encode.py` so that more modules could use it.

**Pull request merged**
