### PR TITLE
release notes and url updates

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY
Updates release notes and url's in our documentation.

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by IBMAnsibleHelper** [comment]
Exception: No such property: True for class: groovy.lang.Binding

**Comment by IBMAnsibleHelper** [comment]
Exception: null

**Comment by IBMAnsibleHelper** [comment]
Exception: null

**Comment by IBMAnsibleHelper** [comment]
Exception: null

**Comment by IBMAnsibleHelper** [comment]
Exception: null

**Comment by IBMAnsibleHelper** [comment]
Exception: null

**Comment by IBMAnsibleHelper** [comment]
Exception: One or more pytest testcases failed! 
 ============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.0, py-1.8.1, pluggy-0.13.1
ansible: 2.9.6
rootdir: /var/lib/jenkins/workspace/zos-ansible-2/ibm_zos_core/tests, inifile: pytest.ini
plugins: ansible-2.2.2, mock-1.12.1
collected 591 items

functional/module_utils/test_arg_parser.py ............................. [  4%]
..............................................................           [ 15%]
functional/modules/test_zos_copy_func.py FLoading callback plugin unnamed of type old, v1.0 from /usr/local/lib/python3.7/site-packages/pytest_ansible/module_dispatcher/v28.py
META: ran handlers
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/collections.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/__init__.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/_collections_compat.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/sys_info.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/process.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/text/__init__.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/parameters.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/text/converters.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/_json_compat.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/_utils.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/text/formatters.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/file.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/validation.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/distro/__init__.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/distro/_distro.py
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/commands/command.py
Pipelining is enabled.
<ec33012a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec33012a.vmec.svl.ibm.com> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<ec33012a.vmec.svl.ibm.com> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<ec33012a.vmec.svl.ibm.com> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="omvsadm")
<ec33012a.vmec.svl.ibm.com> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<ec33012a.vmec.svl.ibm.com> SSH: PlayContext set ssh_common_args: ()
<ec33012a.vmec.svl.ibm.com> SSH: PlayContext set ssh_extra_args: ()
<ec33012a.vmec.svl.ibm.com> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/jenkins/.ansible/cp/4ea700d856)
<ec33012a.vmec.svl.ibm.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o ControlPath=/home/jenkins/.ansible/cp/4ea700d856 ec33012a.vmec.svl.ibm.com '/bin/sh -c '"'"'export _BPXK_AUTOCVT=ON ; export _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' ; export _TAG_REDIR_ERR=txt ; export _TAG_REDIR_IN=txt ; export _TAG_REDIR_OUT=txt ; export LANG=C ; export ZOAU_ROOT=/u/omvsadm/mvsutil ; export ZOAU_HOME=/u/omvsadm/mvsutil ; export LIBPATH=/u/omvsadm/mvsutil/lib:/usr/lpp/izoda/v110/anaconda/lib:/lib:/usr/lib:. ; export ZOAUTIL_DIR=/u/omvsadm/mvsutil ; export PYTHONPATH=/u/omvsadm/mvsutil/lib ; export PATH=/u/omvsadm/mvsutil/bin:/usr/lpp/izoda/v110/anaconda/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin ; /usr/lpp/izoda/v110/anaconda/bin/python3.6 && sleep 0'"'"''
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/pytest.py", line 101, in <module>
    raise SystemExit(pytest.main())
  File "/usr/local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 92, in main
    config=config
  File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 233, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 226, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.7/site-packages/_pytest/terminal.py", line 681, in pytest_sessionfinish
    outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.7/site-packages/_pytest/runner.py", line 76, in pytest_sessionfinish
    session._setupstate.teardown_all()
  File "/usr/local/lib/python3.7/site-packages/_pytest/runner.py", line 319, in teardown_all
    self._pop_and_teardown()
  File "/usr/local/lib/python3.7/site-packages/_pytest/runner.py", line 292, in _pop_and_teardown
    self._teardown_with_finalization(colitem)
  File "/usr/local/lib/python3.7/site-packages/_pytest/runner.py", line 312, in _teardown_with_finalization
    self._callfinalizers(colitem)
  File "/usr/local/lib/python3.7/site-packages/_pytest/runner.py", line 309, in _callfinalizers
    raise val.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/_pytest/runner.py", line 300, in _callfinalizers
    fin()
  File "/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py", line 872, in finish
    raise val.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py", line 865, in finish
    func()
  File "/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py", line 795, in _teardown_yield_fixture
    next(it)
  File "/var/lib/jenkins/workspace/zos-ansible-2/ibm_zos_core/tests/conftest.py", line 67, in ansible_zos_module
    clean_logs(adhoc)
  File "/var/lib/jenkins/workspace/zos-ansible-2/ibm_zos_core/tests/conftest.py", line 39, in clean_logs
    adhoc.all.command(cmd="opercmd '$PJ(*)'")
  File "/usr/local/lib/python3.7/site-packages/pytest_ansible/module_dispatcher/v28.py", line 145, in _run
    raise AnsibleConnectionFailure("Host unreachable", dark=cb.unreachable, contacted=cb.contacted)
pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable

**Comment by IBMAnsibleHelper** [comment]
Exception: One or more pytest testcases failed! 
 ============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.0, py-1.8.1, pluggy-0.13.1
ansible: 2.9.6
rootdir: /var/lib/jenkins/workspace/zos-ansible-2/ibm_zos_core/tests, inifile: pytest.ini
plugins: ansible-2.2.2, mock-1.12.1
collected 591 items

functional/module_utils/test_arg_parser.py ............................. [  4%]
..............................................................           [ 15%]
functional/modules/test_zos_copy_func.py ............................... [ 20%]
.....................................................                    [ 29%]
functional/modules/test_zos_data_set_func.py FLoading callback plugin unnamed of type old, v1.0 from /usr/local/lib/python3.7/site-packages/pytest_ansible/module_dispatcher/v28.py
META: ran handlers
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/commands/command.py
Pipelining is enabled.
<ec33025a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec33025a.vmec.svl.ibm.com> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<ec33025a.vmec.svl.ibm.com> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<ec33025a.vmec.svl.ibm.com> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="omvsadm")
<ec33025a.vmec.svl.ibm.com> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<ec33025a.vmec.svl.ibm.com> SSH: PlayContext set ssh_common_args: ()
<ec33025a.vmec.svl.ibm.com> SSH: PlayContext set ssh_extra_args: ()
<ec33025a.vmec.svl.ibm.com> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/jenkins/.ansible/cp/da8c6ffc56)
<ec33025a.vmec.svl.ibm.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o ControlPath=/home/jenkins/.ansible/cp/da8c6ffc56 ec33025a.vmec.svl.ibm.com '/bin/sh -c '"'"'export _BPXK_AUTOCVT=ON ; export _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' ; export _TAG_REDIR_ERR=txt ; export _TAG_REDIR_IN=txt ; export _TAG_REDIR_OUT=txt ; export LANG=C ; export ZOAU_ROOT=/u/omvsadm/mvsutil ; export ZOAU_HOME=/u/omvsadm/mvsutil ; export LIBPATH=/u/omvsadm/mvsutil/lib:/u/oeusr01/usr/lpp/IBM/cyp/v3r8/pyz/lib:/lib:/usr/lib:. ; export ZOAUTIL_DIR=/u/omvsadm/mvsutil ; export PYTHONPATH=/u/omvsadm/mvsutil/lib ; export PATH=/u/omvsadm/mvsutil/bin:/u/oeusr01/usr/lpp/IBM/cyp/v3r8/pyz/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin ; /u/oeusr01/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3.8 && sleep 0'"'"''
<ec33025a.vmec.svl.ibm.com> (0, b'\n{"cmd": ["opercmd", "$PJ(*)"], "stdout": "EC33025A  2020245  14:33:16.02             ISF031I CONSOLE OMVSADM ACTIVATED\\nEC33025A  2020245  14:33:16.02            -$PJ(*)\\nEC33025A  2020245  14:33:16.07  JOB00108   $HASP890 JOB(CREPDS)\\n                                           $HASP890 JOB(CREPDS)    STATUS=(ON PRT1/STL1,ON PRT4/STL1),\\n                                           $HASP890                CLASS=R,PRIORITY=1,SYSAFF=(ANY),\\n                                           $HASP890                HOLD=(NONE),PURGE=YES\\nEC33025A  2020245  14:33:16.08  JOB00110   $HASP890 JOB(CREKSDS)\\n                                           $HASP890 JOB(CREKSDS)   STATUS=(ON PRT2/STL1,ON PRT3/STL1),\\n                                           $HASP890                CLASS=R,PRIORITY=1,SYSAFF=(ANY),\\n                                           $HASP890                HOLD=(NONE),PURGE=YES", "stderr": "", "rc": 0, "start": "2020-09-01 21:33:15.288985", "end": "2020-09-01 21:33:17.125774", "delta": "0:00:01.836789", "changed": true, "invocation": {"module_args": {"_raw_params": "opercmd \'$PJ(*)\'", "warn": true, "_uses_shell": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}}\n', b'OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 56\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
META: ran handlers
META: ran handlers
Loading callback plugin unnamed of type old, v1.0 from /usr/local/lib/python3.7/site-packages/pytest_ansible/module_dispatcher/v28.py
META: ran handlers
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/commands/command.py
Pipelining is enabled.
<ec33025a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec33025a.vmec.svl.ibm.com> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<ec33025a.vmec.svl.ibm.com> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<ec33025a.vmec.svl.ibm.com> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="omvsadm")
<ec33025a.vmec.svl.ibm.com> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<ec33025a.vmec.svl.ibm.com> SSH: PlayContext set ssh_common_args: ()
<ec33025a.vmec.svl.ibm.com> SSH: PlayContext set ssh_extra_args: ()
<ec33025a.vmec.svl.ibm.com> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/jenkins/.ansible/cp/da8c6ffc56)
<ec33025a.vmec.svl.ibm.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o ControlPath=/home/jenkins/.ansible/cp/da8c6ffc56 ec33025a.vmec.svl.ibm.com '/bin/sh -c '"'"'export _BPXK_AUTOCVT=ON ; export _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' ; export _TAG_REDIR_ERR=txt ; export _TAG_REDIR_IN=txt ; export _TAG_REDIR_OUT=txt ; export LANG=C ; export ZOAU_ROOT=/u/omvsadm/mvsutil ; export ZOAU_HOME=/u/omvsadm/mvsutil ; export LIBPATH=/u/omvsadm/mvsutil/lib:/u/oeusr01/usr/lpp/IBM/cyp/v3r8/pyz/lib:/lib:/usr/lib:. ; export ZOAUTIL_DIR=/u/omvsadm/mvsutil ; export PYTHONPATH=/u/omvsadm/mvsutil/lib ; export PATH=/u/omvsadm/mvsutil/bin:/u/oeusr01/usr/lpp/IBM/cyp/v3r8/pyz/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin ; /u/oeusr01/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3.8 && sleep 0'"'"''
<ec33025a.vmec.svl.ibm.com> (0, b'\n{"cmd": ["uname", "-n"], "stdout": "EC33025A", "stderr": "", "rc": 0, "start": "2020-09-01 21:33:18.083106", "end": "2020-09-01 21:33:18.252476", "delta": "0:00:00.169370", "changed": true, "invocation": {"module_args": {"_raw_params": "uname -n", "warn": true, "_uses_shell": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}}\n', b'OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 56\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
META: ran handlers
META: ran handlers
Loading callback plugin unnamed of type old, v1.0 from /usr/local/lib/python3.7/site-packages/pytest_ansible/module_dispatcher/v28.py
META: ran handlers
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/basic.py
Using module_utils file ansible_collections
Using module_utils file ansible_collections/ibm/ibm_zos_core/plugins/module_utils
Using module_utils file ansible_collections/ibm/ibm_zos_core/plugins
Using module_utils file ansible_collections/ibm/ibm_zos_core
Using module_utils file ansible_collections/ibm/ibm_zos_core/plugins/module_utils/better_arg_parser
Using module_utils file ansible_collections/ibm
Using module_utils file ansible_collections/ibm/ibm_zos_core/plugins/module_utils/import_handler
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/text/__init__.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/_utils.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/parameters.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/text/formatters.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/validation.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/__init__.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/_json_compat.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/_collections_compat.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/file.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/text/converters.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/sys_info.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/process.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/common/collections.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/distro/__init__.py
Using module_utils file /usr/local/lib/python3.7/site-packages/ansible/module_utils/distro/_distro.py
Using module file /var/lib/jenkins/workspace/zos-ansible-2/ibm_zos_core/plugins/modules/zos_operator_action_query.py
Pipelining is enabled.
<ec33025a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec33025a.vmec.svl.ibm.com> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<ec33025a.vmec.svl.ibm.com> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<ec33025a.vmec.svl.ibm.com> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="omvsadm")
<ec33025a.vmec.svl.ibm.com> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<ec33025a.vmec.svl.ibm.com> SSH: PlayContext set ssh_common_args: ()
<ec33025a.vmec.svl.ibm.com> SSH: PlayContext set ssh_extra_args: ()
<ec33025a.vmec.svl.ibm.com> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/jenkins/.ansible/cp/da8c6ffc56)
<ec33025a.vmec.svl.ibm.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o ControlPath=/home/jenkins/.ansible/cp/da8c6ffc56 ec33025a.vmec.svl.ibm.com '/bin/sh -c '"'"'export _BPXK_AUTOCVT=ON ; export _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' ; export _TAG_REDIR_ERR=txt ; export _TAG_REDIR_IN=txt ; export _TAG_REDIR_OUT=txt ; export LANG=C ; export ZOAU_ROOT=/u/omvsadm/mvsutil ; export ZOAU_HOME=/u/omvsadm/mvsutil ; export LIBPATH=/u/omvsadm/mvsutil/lib:/u/oeusr01/usr/lpp/IBM/cyp/v3r8/pyz/lib:/lib:/usr/lib:. ; export ZOAUTIL_DIR=/u/omvsadm/mvsutil ; export PYTHONPATH=/u/omvsadm/mvsutil/lib ; export PATH=/u/omvsadm/mvsutil/bin:/u/oeusr01/usr/lpp/IBM/cyp/v3r8/pyz/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin ; /u/oeusr01/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3.8 && sleep 0'"'"''
<ec33025a.vmec.svl.ibm.com> (0, b'\n{"changed": false, "actions": [], "invocation": {"module_args": {"system": "EC33025A", "message_id": null, "job_name": null}}}\n', b'OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 56\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
META: ran handlers
META: ran handlers


=================================== FAILURES ===================================
_ test_data_set_catalog_and_uncatalog[\n//CREPDS    JOB (T043JM,JM00,1,0,0,0),'CREATE PDS',CLASS=R,\n//             MSGCLASS=X,MSGLEVEL=1,NOTIFY=OMVSADM\n//STEP1    EXEC PGM=IDCAMS\n//SYSPRINT DD  SYSOUT=A\n//SYSIN    DD   *\n     ALLOC -\n           DSNAME('USER.PRIVATE.TESTDS') -\n           NEW -\n           VOL(000000) -\n           DSNTYPE(PDS)\n/*\n] _

ansible_zos_module = <pytest_ansible.host_manager.v28.HostManagerV28 object at 0x7fb603293a90>
jcl = "\n//CREPDS    JOB (T043JM,JM00,1,0,0,0),'CREATE PDS',CLASS=R,\n//             MSGCLASS=X,MSGLEVEL=1,NOTIFY=OMVSADM\n/...n           DSNAME('USER.PRIVATE.TESTDS') -\n           NEW -\n           VOL(000000) -\n           DSNTYPE(PDS)\n/*\n"

    @pytest.mark.parametrize(
        "jcl",
        [PDS_CREATE_JCL, KSDS_CREATE_JCL, RRDS_CREATE_JCL, ESDS_CREATE_JCL, LDS_CREATE_JCL],
    )
    def test_data_set_catalog_and_uncatalog(ansible_zos_module, jcl):
        hosts = ansible_zos_module
        results = hosts.all.zos_data_set(
            name=DEFAULT_DATA_SET_NAME, state="cataloged", volumes=DEFAULT_VOLUME
        )
        results = hosts.all.zos_data_set(name=DEFAULT_DATA_SET_NAME, state="absent")
        hosts.all.file(path=TEMP_PATH, state="directory")
        hosts.all.shell(cmd="echo {0} > {1}/SAMPLE".format(quote(jcl), TEMP_PATH))
        results = hosts.all.zos_job_submit(
            src=TEMP_PATH + "/SAMPLE", location="USS", wait=True
        )
        hosts.all.file(path=TEMP_PATH, state="absent")
        # verify data set creation was successful
        for result in results.contacted.values():
>           assert result.get("jobs")[0].get("ret_code").get("msg_code") == "0000"
E           TypeError: 'NoneType' object is not subscriptable

functional/modules/test_zos_data_set_func.py:140: TypeError
================== 1 failed, 175 passed in 812.21s (0:13:32) ===================

**Comment by IBMAnsibleHelper** [comment]
Exception: One or more pytest testcases failed! 
 ============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-5.3.0, py-1.9.0, pluggy-0.13.1
ansible: 2.9.4
rootdir: /var/lib/jenkins/workspace/zos-ansible-2/ibm_zos_core/tests, inifile: pytest.ini
plugins: ansible-2.2.2, mock-1.12.1
collected 232 items / 1 error / 231 selected

==================================== ERRORS ====================================
_________ ERROR collecting functional/modules/test_zos_encode_func.py __________
ImportError while importing test module '/var/lib/jenkins/workspace/zos-ansible-2/ibm_zos_core/tests/functional/modules/test_zos_encode_func.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
functional/modules/test_zos_encode_func.py:7: in <module>
    from shellescape import quote
E   ModuleNotFoundError: No module named 'shellescape'
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.25s ===============================

**Comment by ddimatos** [comment]
This had passed in our prior CI/CD, technical issues are preventing reruns from displaying it passed.

**Pull request merged**
