### PR TITLE
Changed the encoding options to suboptions

### PR DESCRIPTION
**Pull request by rexemin**
##### SUMMARY

Addresses JIRA-1978, an enhancement for the `zos_encode` module. Instead of using `from_encoding` and `to_encoding` to define the encoding conversion, the module now uses the interface found in all the other modules of the collection, i.e., an `encoding` parameter with suboptions `from` and `to`.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

zos_encode

##### ADDITIONAL INFORMATION

Before this change, all other modules of the collection that can handle encoding conversion between files and datasets used the same interface for defining the way the conversion happened, except for `zos_encode`. The purpose of this PR is to bring consistency across the interfaces of all modules in the collection.

@fernandofloresg brought up a really important point about supporting the old interface for users that already have working playbooks. Should we keep the old options `from_encoding` and `to_encoding` or just keep the new suboptions? Do note that the current state of `zos_encode` in this branch deleted all references to the old options, but they can be brought in again without too much problem.

### CODE REVIEW

**Review by richp405 — APPROVED** [review]
Looks good, and the suboptions definitely are the cleaner approach.

**Comment by ddimatos** [comment]
image
http://sprinkles1.fyre.ibm.com:8080/job/zosAnsible/1085/consoleText

**Review by ddimatos — APPROVED** [review]
@rexemin - changes look good, at this point I am waiting only for regression to run otherwise the code looks ready to merge. Ill merge it when regression completes.

**Comment by ddimatos** [comment]
I found a couple of other module test cases that used the older `zos_encode` module options `from_encoding`  and `to_encoding` and updated them.

For reference, you can also use the dependencyfinder.py to check for such inter-dependent calls:
`python dependencyfinder.py -p .. -b origin/dev -m`
yields:
```
../tests/functional/modules/test_zos_encode_func.py 
../tests/functional/modules/test_zos_blockinfile_func.py 
../tests/functional/modules/test_zos_lineinfile_func.py
```

**Comment by ddimatos** [comment]
image

Internal regression [link/log](http://sprinkles1.fyre.ibm.com:8080/job/zosAnsible/1088/consoleText)

**Pull request merged**
