### PR TITLE
Merge version 1.3.4 release content to support branch

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY

- `zos_ssh` connection plugin was updated to correct a bug in Ansible that

   would result in playbook task `retries` overriding the SSH connection
   `retries`. This is resolved by renaming the `zos_ssh` option
   `retries` to `reconnection_retries`. The update addresses users of
   `ansible-core` v2.9 which continues to use `retries` and users of
   `ansible-core` v2.11 or later which uses `reconnection_retries`.  
- This also resolves a bug in the connection that referenced a deprecated
   constant.  
- This change also introduces the use of changelog and includes all the backdated changes and fragments for historical purposes. 
- `Renames requirements-zos-core.txt` to `requirements.txt`
##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ddimatos** [comment]
Ran the latest galaxy importer 0.4.5 to ensure compliance when released to Hub and Galaxy with no issues:
```
(venv) python -m galaxy_importer.main ibm-ibm_zos_core-1.3.4.tar.gz
Importing with galaxy-importer 0.4.5
Getting doc strings via ansible-doc
Finding content inside collection
Loading module zos_data_set
Loading module zos_ping
Loading module zos_encode
Loading module zos_job_output
Loading module zos_operator_action_query
Loading module zos_find
Loading module zos_mvs_raw
Loading module zos_backup_restore
Loading module zos_lineinfile
Loading module zos_copy
Loading module zos_apf
Loading module zos_tso_command
Loading module zos_job_query
Loading module zos_job_submit
Loading module zos_operator
Loading module zos_fetch
Loading module zos_blockinfile
Loading module_utils better_arg_parser
Loading module_utils mvs_cmd
Loading module_utils backup
Loading module_utils system
Loading module_utils encode
Loading module_utils job
Loading module_utils vtoc
Loading module_utils zos_mvs_raw
Loading module_utils copy
Loading module_utils ansible_module
Loading module_utils file
Loading module_utils dd_statement
Loading module_utils data_set
Loading module_utils import_handler
Loading action zos_ping
Loading action zos_copy
Loading action zos_job_submit
Loading action zos_fetch
Loading connection zos_ssh
Loading filter wtor
WARNING: Ignore files skip ansible-test sanity tests, found ignore-2.11.txt with 31 statement(s)
WARNING: Ignore files skip ansible-test sanity tests, found ignore-2.10.txt with 32 statement(s)
WARNING: Ignore files skip ansible-test sanity tests, found ignore-2.12.txt with 32 statement(s)
WARNING: Ignore files skip ansible-test sanity tests, found ignore-2.9.txt with 32 statement(s)
Collection loading complete
Importer processing completed successfully
```

**Comment by ddimatos** [comment]
image

See log http://sprinkles1.fyre.ibm.com:8080/job/zosAnsible/688/

**Comment by ddimatos** [comment]
@rexemin 
That was a good catch, I will update, the only thing that I have to tweak is the `zos_lineinfile` because we don't have a 1.2.0 release in Automation Hub because there was a issue with the upload so we had to bump the version to 1.2.1 thus I have marked `zos_lineinfile` releasing as 1.2.1. 

1.2.1 and 1.2.0 was the same code, unfortunately we had an issue with the galaxy importer and had to bump the version. 

I corrected the rest.

**Review by rexemin — APPROVED** [review]
Thanks for updating the changelog for the 3 modules I mentioned. As I said before, everything looks pretty good.

**Comment by ddimatos** [comment]
[Ran full regression and success](http://sprinkles1.fyre.ibm.com:8080/job/zosAnsible/735/consoleText).
image

**Pull request merged**
