### PR TITLE
Enhancement/423/zos copy add data set member alias support

### LINKED ISSUE #423: [Enhancement] [zos_copy]  Support Data Set member Aliases
### Enhancement description

This is an enhancement because aliases were not intentionally supported.

# Enhancement

The `zos_copy` module does not copy any aliases, take for example the snippet below:
```
zos_copy:
 src: SYS2.MQMM001.SCSQSNLE(*)
 dest: SYS2.MQM.LPALIB.ANS
 remote_src: true
```

Where the data set  `SYS2.MQMM001.SCSQSNLE` when browsed has:
```
Name Prompt Alias-of Size
_________ CSQNL28E 00000A28
_________ CSQ3ECMX CSQNL28E 00000A28
```

In this case, only the member would be copied to the dest and not the alias.

## Source Problem
`zos_copy` uses ZOAU to list the members with source similar to `members = list(map(str.strip, datasets.list_members(src)))`  only no Aliases are returned which results in `zos_copy` not knowing about the alias and passing the listing `zos_copy` handler `copy_to_member` which ultimately invokes `datasets._copy(new_src, dest)` on a list does not include an alias.

# Notes
- The issue originally was in internal archive `C01E25VTZ3L/p1622058177044000`
- There are a number of ways to handle this, requesting ZOAU `mls` and `dls` support reading aliases
- An alias is like a *nix symlink, we would not want to copy an alias such that it results in a physical copy, that would defeat the purpose. We would want to ensure/check if something is an alias and make another alias, this should either be done by zos_copy or zoau methods (ensure we don't make another physical copy)
- Some ideas if we want to do this solely in zos_copy is to remove the `datasets.list_members(src) `call and insert our own commands or REXX that would check if a member is an Alias before doing a copy, basically separating members from aliases and then for the Aliases we could run a command like so in TSO to create the Alias for the `zos_copy` function `RENAME 'IMSTESTL.DIMATO.JCLCOPY(DATA)' 'IMSTESTL.DIMATO.JCLCOPY(DATAX)' ALIAS` and to list the members and Aliases `LISTDS 'IMSTESTL.DIMATO.JCLCOPY' MEMBERS`

image

# Comments
## From @adn1107 
IEBCOPY COPYGROUP option [can be used to copy aliases](https://www.ibm.com/docs/en/zos/2.1.0?topic=program-copying-objects-copygrp-copygroup-statements) 

It is recommended that you use the COPYGRP or COPYGROUP statement to copy PDS load modules or PDSE program objects and their aliases from or to a PDSE data set. Program objects can have aliases that are longer than eight characters. Using the COPYGRP or COPYGROUP statement will ensure that these longer aliases are copied along with their member.

Use the COPYGRP or COPYGROUP statement to begin a group copy, unload, or load. A group consists of a member and all of its aliases. COPYGRP or COPYGROUP treats the group as a single entity.

COPYGRP can be used to copy a data set when either the input data set or the output data set, or both, are PDSE:
PDSE to PDSE
PDSE to PDS
PDS to PDSE
COPYGROUP can be used to copy a data set when either the input data set or the output data set, or both, are PDS or PDSE:
PDSE to PDSE
PDSE to PDS
PDS to PDSE
PDS to PDS
For unloading groups:
Using COPYGRP: PDSE to PS
Using COPYGROUP: PDSE to PS, or PDS to PS
For loading groups:
Using COPYGRP: PS to PDSE
Using COPYGROUP: PS to PDSE, or PS to PDS
If neither data set is a PDSE, the request is treated the as a COPY operation subject to the syntax requirements of COPYGRP.

When using the COPYGRP or COPYGROUP statement:

    All aliases in a group will be copied with the member or neither the aliases or the member in a group will be copied.
    There can be only one INDD per copy operation.
    You can use the SELECT statement to selectively copy members. Either the member name or an alias can be specified to copy the member and all of its aliases.
    Do not indicate replace (R) on the SELECT statement.
    The EXCLUDE statement is not supported.

### Ansible module

zos_copy

### PR DESCRIPTION
**Pull request by ketankelkar**
##### SUMMARY
Introduces a new option `aliases` in the zos_copy module to preserve aliases when copying executable libraries (MVS or USS) to partitioned data sets.

Fixes #423 
see supporting issue #1015 

This also addresses - #621 
##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Review by richp405 — CHANGES_REQUESTED** [review]
I believe this needs a changelog/fragment for approval.

**Review by rexemin — COMMENTED** [review]
Looks good. As Rich said, it needs a changelog fragment

**Review by richp405 — APPROVED** [review]
Thanks for the changelog.

**Review by fernandofloresg — APPROVED** [review]
Looks good to me, great that you cleaned the test cases and implicitly tested the newly added option "LIBRARY".

**Comment by ketankelkar** [comment]
above commits were comments/docs, re-ran that portion of the pipeline for validation - 
Screenshot 2023-10-11 at 1 55 36 PM

**Pull request merged**
