### PR TITLE
Deprecate debug=true in zos_blockinfile and set as_json=true

### LINKED ISSUE #711: [Enhancement] [zos_lineinfile] [zos_blockinfile] Leverage new JSON flag for datasets.blockinfile operations
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_blockinfile

### Enhancement or feature description

ZOAU 1.2.3 delivered a new variable flag to provide JSON output when interacting with the datasets Python API functionality. Historically, this was provided through the debug flag only. Ansible Core should switch to this new flag so that debug operations can be reserved for actual debug activities only.

**Acceptance Criteria**
Given the z/os Core Collection
When a user invokes lineinfile or blockinfile functionality
Then activity is driven through the ZOAU's datasets Python API with the JSON flag

**Requirements**
-Deprecate debug=true in zos_blockinfile and zos_linefile, or other modules leveraging datasets.blockinfile as needed
-Leverage as_json=true for datasets.blockinfile calls

**Additional Context**
datasets.blockinfile(as_json=true)

### PR DESCRIPTION
**Pull request by AndreMarcel99**
##### SUMMARY
Deprecate debug option in zos_blockinfile and set as_json option

Fixes #711 

##### ISSUE TYPE
- Docs Pull Request

##### ADDITIONAL INFORMATION
Only blockinfile uses the function, because of that only in blockinfile change the request removing debug=true and set as_json=true option

Captura de pantalla 2023-07-20 a la(s) 11 01 57
Captura de pantalla 2023-07-20 a la(s) 11 02 10

### CODE REVIEW

**Comment by fernandofloresg** [comment]
Hi Marcel, the statement fixes #771 looks unrelated to the PR content. Could you point to the correct issue number?

**Comment by AndreMarcel99** [comment]
Done

**Review by fernandofloresg — APPROVED** [review]
Looks good to me. I see the pipeline ran for about 22 minutes. Was there any other test file skipped? Asking because I don't know if this module is use on other test cases.

**Comment by fernandofloresg** [comment]
Also, a recommendation, your PRs are improving in completion and details. Make sure to add the details about the task to the PR as well.

For example, current dev branch has version 1.7.0-beta.1, the task related to this PR is expected to be released into 1.8.0-beta.1, so adding "Do Not Merge" label will give us a visual clue about not merging after 1.7.0-beta.1 has its own branch.

Also, adding the fact that this PR is for 1.8.0-beta.1 will show up in the release board.

Recommend also to add "Waiting for reviewers" label.

Screenshot 2023-07-20 at 12 05 34 PM

**Comment by AndreMarcel99** [comment]
The pipeline run the tests of blockinfile and zos_fetch

**Review by richp405 — APPROVED** [review]
Changes are straightforward.

**Review by ddimatos — APPROVED** [review]
Thank you @AndreMarcel99

**Comment by ddimatos** [comment]
@ketankelkar , you should in a bout a week or two be able to see our code scan pass this false positive now. Scans run on Tuesdays.

**Pull request merged**
