### PR TITLE
Stagging v1.6.0 merge into dev

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY
This is part of issue #733. This merges any bug fixes done for 1.6.0 into the dev (1.7.0-beta.1) and brings meta data current. 

This merged `dev` into `stagging-v1.6.0` , changelog of merge:
```
commit 8c7d4a620227ab483e2b4a4d8e115845e0f0203c (HEAD -> stagging-v1.6.0, origin/stagging-v1.6.0)
Merge: 28985ce3 57032466
Author: ddimatos <dimatos@gmail.com>
Date:   Wed Jun 28 17:57:56 2023 -0700

    Merge branch 'dev' into stagging-v1.6.0

     Conflicts:
            .ansible-lint
            .github/ISSUE_TEMPLATE/bug_issue.yml
            .github/ISSUE_TEMPLATE/collaboration_issue.yml
            .github/ISSUE_TEMPLATE/doc_issue.yml
            .github/ISSUE_TEMPLATE/enabler_issue.yml
            .github/ISSUE_TEMPLATE/enhancement_feature.issue.yml
            .github/ISSUE_TEMPLATE/module_issue.yml
            CHANGELOG.rst
            README.md
            changelogs/.plugin-cache.yaml
            changelogs/changelog.yaml
            docs/source/modules/zos_data_set.rst
            docs/source/modules/zos_job_query.rst
            docs/source/release_notes.rst
            galaxy.yml
            meta/ibm_zos_core_meta.yml
            meta/runtime.yml
            plugins/module_utils/job.py
            plugins/modules/zos_copy.py
            plugins/modules/zos_data_set.py
            scripts/mounts.sh
            scripts/profile-shr
            scripts/profile.sh
            tests/functional/modules/test_zos_copy_func.py
            tests/functional/modules/test_zos_data_set_func.py
```

### CODE REVIEW

**Comment by ddimatos** [comment]
image
Log: job/zosAnsibleAlternate/155/
```
====================== 824 passed in 11031.79s (3:03:51) =======================
```

**Comment by ddimatos** [comment]
@rexemin - included you for a review since I was merging in items fixed in 1.6 into our latest branch.
@ketankelkar - included you as the fix for version check was i 1.6 and coming to 1.7

**Review by richp405 — APPROVED** [review]
Pretty straightforward.

**Review by rexemin — APPROVED** [review]
Looks good.

**Pull request merged**
