### PR TITLE
Updates for "non-utf8 chars" Deprecation Warning

### LINKED ISSUE #988: [Enabler] Implement the solution for the UTF-8 warning
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

_No response_

### Enabler description

This is part of collaboration #983.
 Implement the proposed solution for the UTF-8 warning.

### PR DESCRIPTION
**Pull request by ketankelkar**
##### SUMMARY

These changes update the "errors" algorithm when non-printable characters are detected by python specifically for calls to the ansible util `run_command`. The new "replace" algorithm replaces any non-printable chars in the stdout/stderr streams with �, which falls under utf-8 and does not raise the deprecation warning that non-utf8 chars in stdout will be treated as error starting with ansible-core:218.

- Fixes #988 

##### ISSUE TYPE
- Enabler Pull Request

##### ADDITIONAL INFORMATION
I found that most of the affected function calls for most of the modules are internal checks (eg check for data_set_name in listcat output). As these changes are hidden from the user, I marked them under `trivial` in the changelog. However, I found 3 modules where the output is altered by these changes. The only change really is that the new � symbol shows up in the output. For the modules, `zos_script`, `zos_tso_command`, and `zos_mvs_raw`, I've marked the changes in the changelog as `minor_changes` since the user could notice these changes.

### CODE REVIEW

**Comment by ketankelkar** [comment]
The output of the dependencyfinder:
```
../tests/functional/modules/test_zos_archive_func.py ../tests/functional/modules/test_zos_find_func.py ../tests/functional/modules/test_zos_data_set_func.py ../tests/functional/modules/test_zos_fetch_func.py ../tests/functional/modules/test_zos_copy_func.py ../tests/functional/modules/test_zos_job_output_func.py ../tests/functional/modules/test_zos_job_query_func.py ../tests/functional/modules/test_zos_backup_restore.py ../tests/functional/modules/test_zos_job_submit_func.py ../tests/unit/test_zos_backup_restore_unit.py ../tests/functional/modules/test_zos_unarchive_func.py ../tests/functional/modules/test_zos_blockinfile_func.py ../tests/functional/modules/test_module_security.py ../tests/functional/modules/test_zos_lineinfile_func.py ../tests/functional/modules/test_zos_script_func.py ../tests/functional/modules/test_zos_mount_func.py ../tests/functional/modules/test_zos_volume_init_func.py ../tests/functional/modules/test_zos_apf_func.py ../tests/functional/modules/test_zos_tso_command_func.py ../tests/functional/modules/test_zos_mvs_raw_func.py ../tests/functional/modules/test_zos_encode_func.py ../tests/unit/test_zos_mvs_raw_unit.py
```

alphabetized:
```
tests/functional/modules/test_zos_apf_func.py 
tests/functional/modules/test_zos_archive_func.py 
tests/functional/modules/test_zos_backup_restore.py 
tests/functional/modules/test_zos_blockinfile_func.py 
tests/functional/modules/test_zos_copy_func.py 
tests/functional/modules/test_zos_data_set_func.py 
tests/functional/modules/test_zos_encode_func.py 
tests/functional/modules/test_zos_find_func.py 
tests/functional/modules/test_zos_fetch_func.py 
tests/functional/modules/test_zos_job_output_func.py 
tests/functional/modules/test_zos_job_query_func.py 
tests/functional/modules/test_zos_job_submit_func.py 
tests/functional/modules/test_zos_lineinfile_func.py 
tests/functional/modules/test_zos_mount_func.py 
tests/functional/modules/test_zos_mvs_raw_func.py 
tests/functional/modules/test_zos_script_func.py 
tests/functional/modules/test_zos_tso_command_func.py 
tests/functional/modules/test_zos_unarchive_func.py 
tests/functional/modules/test_zos_volume_init_func.py 

tests/unit/test_zos_backup_restore_unit.py 
tests/unit/test_zos_mvs_raw_unit.py

tests/functional/modules/test_module_security.py 
```

**Review by richp405 — APPROVED** [review]
wow... lots of changes for a nasty little character.. nice!

**Review by rexemin — COMMENTED** [review]
Looks good, I'm just seeing there are conflicts in one test for zos_mvs_raw, as soon as that gets fixed, I'll approve

**Comment by ketankelkar** [comment]
The merge changed the following files, I ran the pipeline just to be safe:
image


image
image
image

**Review by rexemin — APPROVED** [review]

**Pull request merged**
