### PR TITLE
Release v1.3.0 beta.1

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY

**New Modules**
  * ``zos_apf`` - Add or remove libraries to and from Authorized Program Facility (APF).
  * ``zos_backup_restore`` - Backup and restore data sets and volumes.
  * ``zos_blockinfile`` - Manage block of multi-line textual data on z/OS.
  * ``zos_find`` - Find matching data sets.

**Bug Fixes**
  * Module ``zos_copy`` was updated to fail gracefully when a it encounters a non-zero return code.
  * Action plugin ``zos_copy`` was updated to support Python 2.7.
  * Module ``zos_tso_command`` support was added for when the command output contained special characters.
  * Module ``zos_job_submit`` referenced a non-existent option and was corrected to **wait_time_s**.

##### ISSUE TYPE
- New Module Pull Request

### CODE REVIEW

**Comment by IBMAnsibleHelper** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 2 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/zos_apf.py:0:0: doc-default-does-not-match-spec: Argument 'marker' in argument_spec found in persistent defines default as ('/* {mark} ANSIBLE MANAGED BLOCK <timestamp> */') but documentation defines default as ('/\\* {mark} ANSIBLE MANAGED BLOCK <timestamp> \\*/')
ERROR: plugins/modules/zos_apf.py:220:3: invalid-examples: EXAMPLES is not valid YAML
ERROR: Found 1 yamllint issue(s) which need to be resolved:
ERROR: plugins/modules/zos_apf.py:220:3: error: EXAMPLES: syntax error: could not find expected ':' (syntax)
ERROR: The 2 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by IBMAnsibleHelper** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 rstcheck issue(s) which need to be resolved:
ERROR: docs/source/modules/zos_apf.rst:182:0: Inline emphasis start-string without end-string.
ERROR: Found 1 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/zos_apf.py:220:3: invalid-examples: EXAMPLES is not valid YAML
ERROR: Found 1 yamllint issue(s) which need to be resolved:
ERROR: plugins/modules/zos_apf.py:220:3: error: EXAMPLES: syntax error: could not find expected ':' (syntax)
ERROR: The 3 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by IBMAnsibleHelper** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 ignores issue(s) which need to be resolved:
ERROR: tests/sanity/ignore-2.9.txt:30:48: Error code cannot contain spaces
ERROR: Found 1 rstcheck issue(s) which need to be resolved:
ERROR: docs/source/modules/zos_apf.rst:182:0: Inline emphasis start-string without end-string.
ERROR: Found 1 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/zos_apf.py:220:3: invalid-examples: EXAMPLES is not valid YAML
ERROR: Found 1 yamllint issue(s) which need to be resolved:
ERROR: plugins/modules/zos_apf.py:220:3: error: EXAMPLES: syntax error: could not find expected ':' (syntax)
ERROR: The 4 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by IBMAnsibleHelper** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 rstcheck issue(s) which need to be resolved:
ERROR: docs/source/modules/zos_apf.rst:182:0: Inline emphasis start-string without end-string.
ERROR: The 1 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by IBMAnsibleHelper** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 rstcheck issue(s) which need to be resolved:
ERROR: docs/source/modules/zos_apf.rst:182:0: Inline emphasis start-string without end-string.
ERROR: Found 1 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/zos_apf.py:218:3: invalid-examples: EXAMPLES is not valid YAML
ERROR: Found 1 yamllint issue(s) which need to be resolved:
ERROR: plugins/modules/zos_apf.py:218:3: error: EXAMPLES: syntax error: expected <block end>, but found '-' (syntax)
ERROR: The 3 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by IBMAnsibleHelper** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 ignores issue(s) which need to be resolved:
ERROR: tests/sanity/ignore-2.9.txt:30:65: Error code cannot contain spaces
ERROR: Found 1 rstcheck issue(s) which need to be resolved:
ERROR: docs/source/modules/zos_apf.rst:182:0: Inline emphasis start-string without end-string.
ERROR: The 2 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by IBMAnsibleHelper** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 ignores issue(s) which need to be resolved:
ERROR: tests/sanity/ignore-2.9.txt:30:41: Sanity test 'rstcheck' does not support error codes
ERROR: Found 1 rstcheck issue(s) which need to be resolved:
ERROR: docs/source/modules/zos_apf.rst:182:0: Inline emphasis start-string without end-string.
ERROR: The 2 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Review by blakeinate — APPROVED** [review]
Looks perfect, thanks for all the time and effort you have put into making this release possible @ddimatos. Also really appreciate the config link additions to the docs, will be very useful for locating requirements.

**Pull request merged**
