### PR TITLE
Cherry picking 1.9 into dev

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY
This will complete the git issue #1149 which is to merge the changes back upstream.

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by ddimatos** [comment]
```
============================= test session starts ==============================
platform linux -- Python 3.9.17, pytest-7.4.2, pluggy-1.3.0 -- /usr/local/bin/python3
cachedir: .pytest_cache
ansible: 2.15.5
rootdir: /var/lib/jenkins/workspace/ansible-zos-core-dev-1/ibm_zos_core/tests
configfile: pytest.ini
plugins: mock-3.14.0, ansible-4.1.1
collecting ... collected 10 items

tests/functional/modules/test_zos_job_output_func.py::test_zos_job_output_no_job_id PASSED [ 10%]
tests/functional/modules/test_zos_job_output_func.py::test_zos_job_output_invalid_job_id PASSED [ 20%]
tests/functional/modules/test_zos_job_output_func.py::test_zos_job_output_no_job_name PASSED [ 30%]
tests/functional/modules/test_zos_job_output_func.py::test_zos_job_output_invalid_job_name PASSED [ 40%]
tests/functional/modules/test_zos_job_output_func.py::test_zos_job_output_no_owner PASSED [ 50%]
tests/functional/modules/test_zos_job_output_func.py::test_zos_job_output_invalid_owner PASSED [ 60%]
tests/functional/modules/test_zos_job_output_func.py::test_zos_job_output_reject PASSED [ 70%]
tests/functional/modules/test_zos_job_output_func.py::test_zos_job_output_job_exists PASSED [ 80%]
tests/functional/modules/test_zos_job_output_func.py::test_zos_job_output_job_exists_with_filtered_ddname PASSED [ 90%]
tests/functional/modules/test_zos_job_output_func.py::test_zos_job_submit_job_id_and_owner_included PASSED [100%]
```
image

**Comment by ddimatos** [comment]
```
============================= test session starts ==============================
platform linux -- Python 3.9.17, pytest-7.4.2, pluggy-1.3.0 -- /usr/local/bin/python3
cachedir: .pytest_cache
ansible: 2.15.5
rootdir: /var/lib/jenkins/workspace/ansible-zos-core-dev-2/ibm_zos_core/tests
configfile: pytest.ini
plugins: mock-3.14.0, ansible-4.1.1
collecting ... collected 5 items

tests/functional/modules/test_zos_job_query_func.py::test_zos_job_query_func PASSED [ 20%]
tests/functional/modules/test_zos_job_query_func.py::test_zos_job_id_query_multi_wildcards_func PASSED [ 40%]
tests/functional/modules/test_zos_job_query_func.py::test_zos_job_name_query_multi_wildcards_func PASSED [ 60%]
tests/functional/modules/test_zos_job_query_func.py::test_zos_job_id_query_short_ids_func PASSED [ 80%]
tests/functional/modules/test_zos_job_query_func.py::test_zos_job_id_query_short_ids_with_wilcard_func PASSED [100%]
```
image

**Comment by ddimatos** [comment]
```
============================= test session starts ==============================
platform linux -- Python 3.9.17, pytest-7.4.2, pluggy-1.3.0 -- /usr/local/bin/python3
cachedir: .pytest_cache
ansible: 2.15.5
rootdir: /var/lib/jenkins/workspace/ansible-zos-core-dev-3/ibm_zos_core/tests
configfile: pytest.ini
plugins: mock-3.14.0, ansible-4.1.1
collecting ... collected 25 items

tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_PDS[location0] PASSED [  4%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_PDS[location1] PASSED [  8%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_PDS_special_characters PASSED [ 12%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_USS PASSED [ 16%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_LOCAL PASSED [ 20%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_LOCAL_extraR PASSED [ 24%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_LOCAL_BADJCL PASSED [ 28%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_PDS_volume PASSED [ 32%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_PDS_5_SEC_JOB_WAIT_15 PASSED [ 36%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_PDS_30_SEC_JOB_WAIT_60 PASSED [ 40%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_PDS_30_SEC_JOB_WAIT_10_negative PASSED [ 44%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_max_rc[args0] PASSED [ 48%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_max_rc[args1] PASSED [ 52%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_max_rc[args2] PASSED [ 56%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_jinja_template[args0] PASSED [ 60%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_jinja_template[args1] PASSED [ 64%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_jinja_template[args2] PASSED [ 68%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_full_input PASSED [ 72%]
tests/functional/modules/test_zos_job_submit_func.py::test_negative_job_submit_local_jcl_no_dsn PASSED [ 76%]
tests/functional/modules/test_zos_job_submit_func.py::test_negative_job_submit_local_jcl_invalid_user PASSED [ 80%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_local_jcl_typrun_scan PASSED [ 84%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_local_jcl_typrun_copy PASSED [ 88%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_local_jcl_typrun_hold PASSED [ 92%]
tests/functional/modules/test_zos_job_submit_func.py::test_job_submit_local_jcl_typrun_jclhold PASSED [ 96%]
tests/functional/modules/test_zos_job_submit_func.py::test_zoau_bugfix_invalid_utf8_chars PASSED [100%]
```

image

**Review by fernandofloresg — APPROVED** [review]
Corrected a typo and uncommented a section to remove temp files in the managed node  in test cases for zos_job_submit, other than that looks great

**Review by richp405 — APPROVED** [review]
whew!  That was a lot of pickin!

**Review by rexemin — APPROVED** [review]

**Review by AndreMarcel99 — APPROVED** [review]

**Pull request merged**
