### PR TITLE
Testlint

### PR DESCRIPTION
**Pull request by richp405**
##### SUMMARY
This is the 2 changes needed for ansible-lint to work on the dev branch

This is the end of ticket 695: 
https://github.com/ansible-collections/ibm_zos_core/issues/695

##### ISSUE TYPE
- Feature Pull Request: Add ansible-lint scanning to pipeline

##### COMPONENT NAME
Pipeline: allowing Ansible-lint to run without tripping over the sanity/ignore files.
Also updates requirements to 2.11, since 2.9 is now out-of-support.

### CODE REVIEW

**Comment by rexemin** [comment]
Changes look straightforward, just one question: in the issue Demetri mentioned that at some point we'll have to work on fixing the ignores because the requirements for collections will change in 2024, but I couldn't find it, do you know what issue will that be? Or am I understanding that part wrong?

**Comment by richp405** [comment]
> Changes look straightforward, just one question: in the issue Demetri mentioned that at some point we'll have to work on fixing the ignores because the requirements for collections will change in 2024, but I couldn't find it, do you know what issue will that be? Or am I understanding that part wrong?

@rexemin I don't remember that conversation, but he would be right.  I'm "hiding" the error so we can check.  The error (there are at least 100) is that things in the sanity/ignore files are not allowed to be ignored.  I'll look in some threads to see if there are any other approaches.

**Comment by richp405** [comment]
> > Changes look straightforward, just one question: in the issue Demetri mentioned that at some point we'll have to work on fixing the ignores because the requirements for collections will change in 2024, but I couldn't find it, do you know what issue will that be? Or am I understanding that part wrong?
> 
> @rexemin I don't remember that conversation, but he would be right. I'm "hiding" the error so we can check. The error (there are at least 100) is that things in the sanity/ignore files are not allowed to be ignored. I'll look in some threads to see if there are any other approaches.

Interesting... I see comments in a 'merged' doc: https://github.com/ansible-collections/ibm_zos_core/pull/813/files. My concern is the entry is listed as merged, but that's NOT what was in /dev/ yesterday... it shows only 2.9 ignore and a dependency on 2.9...the 813 issue showed ignore on 2.9, 2.10 and 2.11, and a dependency on 2.12.  Not sure where to go with this.

**Comment by richp405** [comment]
Since we have the actual fix work assigned for Q4, I'll close this PR.

**Pull request closed without merging**
