### PR TITLE
Updates to correct use of words in our source

### PR DESCRIPTION
**Pull request by ddimatos**
Signed-off-by: ddimatos <dimatos@gmail.com>

##### SUMMARY
This change works towards removing words in our offering that matter. Cleans up several references. 

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by ketankelkar** [comment]
LGTM except what appears to be a missed "white list" in the comments section:
https://github.com/ansible-collections/ibm_zos_core/blob/e6c9959a4833865f950e1f4eeacbe6f8df68bc8e/docs/source/conf.py#L148

**Comment by ketankelkar** [comment]
LGTM

**Comment by ddimatos** [comment]
Internal [regression link](http://sprinkles1.fyre.ibm.com:8080/job/zosAnsible/822/consoleText) successful 
image

**Comment by ketankelkar** [comment]
draft pr lgtm, this actual one also lgtm

**Review by ketankelkar — APPROVED** [review]
draft pr was fine. this 'official' PR also LGTM

**Pull request merged**
