### PR TITLE
[v1.10.0] [zos_gather_facts] ZOAU 1.3 migration - zos_gather_facts

### LINKED ISSUE #1109: [Enabler] [Dev] [zos_gather_facts] Migrate module, module utilities and test cases to ZOAU 1.3
## Ansible module
`zos_gather_facts`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

With the adoption of ZOAU 1.3, modules, module utilities and test cases may need to be updated according to the [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier). 

APIs changes affecting module:
- Impacted by ZOAU Dataset API: No
- Impacted by ZOAU jobs API: No
- Impacted by the rename of types.py to ztypes.py: No
- Impacted by the contents of module volumes.py having been moved to datasets.py: No
- Impacted by opercmd timeout to milli seconds: No
- Impacted by JSON schema change:  Y (zinfo) - see below where the json response has been encapsulated with a data object
- Impacted by Exceptions schema: No

Review the [zoautil_py datasets module migration doc](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier#changes-to-the-datasets-module).

Note, that the shcema for the `zinfo` command has been encapsulated with a `data` object (#954), this may impact the response Ansible sends with additional encapsulation that needs to be removed or documented as a breaking change with a migration doc. 

For reference the JSON Schema changes with examples should also be reviewed:
https://www.ibm.com/docs/en/zoau/1.3.x?topic=examples-json-schema

#954 - we may cancel this issue if the work is handled on each module

### LINKED ISSUE #1126: [Enabler] [tests/test_zos_gather_facts.py] Migrate module, module utilities and test cases to ZOAU 1.3
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module functional tests

test_zos_gather_facts.py

### Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

With the adoption of ZOAU 1.3, modules, module utilities and test cases will need to be updated according to the [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier). 

APIs changes impacting module:
    - Impacted by ZOAU Dataset API: N
    - Impacted by ZOAU jobs API: N
    - Impacted rename of  types.py to ztypes.py: N
    - Impacted contents of module volumes.py moved to datasets.py: N
    - Impacted by opercmd timeout to milli sec: N
    - Impacted by JSON schema change: Y (zinfo)
    - Impacted by Excecptions schema: N

Additional highlights:
TBD

### PR DESCRIPTION
**Pull request by ketankelkar**
Update module to leverage zoau python api for zinfo.
Update test cases accordingly.

##### SUMMARY
Fixes #1109 
Fixes #1126

The biggest change made here was leveraging the python api available for zinfo rather than constructing and calling a shell command. Much of the validation was repurposed/reused, so the code looks fairly similar.

The minumum ZOAU version has been raised to 1.3.0 since older versions will now break with these newer changes (the python api for zinfo available in prior versions of zoau has changed).

The only error the zinfo python api raises is a ValueError, so the logic handling the BGYSC520xx errors is removed.

##### ISSUE TYPE

- Enabler Pull Request

### CODE REVIEW

**Comment by ketankelkar** [comment]
passes regression-
image

pytests run-
 - ../tests/unit/test_zos_gather_facts.py 
 - ../tests/functional/modules/test_zos_gather_facts_func.py

image

**Review by richp405 — APPROVED** [review]

**Comment by ketankelkar** [comment]
converted back to `Draft Mode` to see if the error handling can be further streamlined

**Comment by ketankelkar** [comment]
Updated and re-ran regression, still looks good:

image


```[Pipeline] echo
Python: Python 3.10 patched
[Pipeline] echo
zoau ver: Zoau 1.3.0
[Pipeline] echo
Ansible: 2.14.1
[Pipeline] echo
Branch: enabler/1109/zos_gather_facts_1.3.0_migration
```

pytests run-

    ../tests/unit/test_zos_gather_facts.py
    ../tests/functional/modules/test_zos_gather_facts_func.py

**Review by fernandofloresg — APPROVED** [review]
Nice work. Liked how you renamed things to adapt to the new paradigm

**Pull request merged**
