### PR TITLE
Enhancement/9108/zos Modify zos_encode functional test suite to not leave tmp files

### PR DESCRIPTION
**Pull request by fernandofloresg**
##### SUMMARY

Modify various tmp directories, added try and finally block statements to clean tmp files created during each test 

##### ISSUE TYPE

- Enhancement Pull Request
##### COMPONENT NAME

tests/functional/modules/test_zos_encode_func.py

##### ADDITIONAL INFORMATION

When running the test suite you get files left behind under tmp folder, first execute the test test_zos_encode_func.py:
`python3 -m pytest --ignore=functional/modules/test_module_security.py --durations=0 --host-pattern=all -Z=/var/lib/jenkins/workspace/zos-multipath-4/ibm_zos_core/configuration.yml ../tests/functional/modules/test_zos_encode_func.py`

SSH into USS and run 
`ls -l tmp`

You would get different tmp files:
# cd /tmp
# ls -laR
.:
total 128
drwxrwxrwt   5 BPXROOT  OMVSGRP     8192 Jul 29 09:50 .
drwxr-xr-x   6 BPXROOT  OMVSGRP     8192 Apr 27  2017 ..
drwxr-xr-x   4 BPXROOT  OMVSGRP     8192 Jul 29 02:40 ansible
drwxr-xr-x   4 BPXROOT  OMVSGRP     8192 Jul 29 01:31 dest
-rw-r--r--   1 BPXROOT  SYS1         188 Jul 29 01:31 encode.data
-rw-r--r--   1 BPXROOT  OMVSGRP      276 Jul 25 09:13 inetd.stdout
drwxr-xr-x   2 BPXROOT  OMVSGRP     8192 Jul 29 01:31 src
-rw-rw-rw-   1 BPXROOT  OMVSGRP     4746 Mar 21 04:15 telnetd.stderr
./ansible:
total 96
drwxr-xr-x   4 BPXROOT  OMVSGRP     8192 Jul 29 02:40 .
drwxrwxrwt   5 BPXROOT  OMVSGRP     8192 Jul 29 09:50 ..
drwxr-xr-x   2 BPXROOT  OMVSGRP     8192 Jul 29 01:35 jcl2
drwxr-xr-x   2 BPXROOT  OMVSGRP     8192 Jul 29 01:35 jcl@2022-07-29-08-35-02-bak
-rw-r--r--   1 BPXROOT  OMVSGRP    10240 Jul 29 01:35 jcl@2022-07-29-08-35-42-bak.tar
./ansible/jcl2:
total 86
drwxr-xr-x   2 BPXROOT  OMVSGRP     8192 Jul 29 01:35 .
drwxr-xr-x   4 BPXROOT  OMVSGRP     8192 Jul 29 02:40 ..
-rw-r--r--   1 BPXROOT  OMVSGRP       80 Jul 29 01:35 SAMPLE
-rw-r--r--   1 BPXROOT  OMVSGRP       80 Jul 29 01:35 SAMPLE2
-rw-r--r--   1 BPXROOT  OMVSGRP       80 Jul 29 01:35 SAMPLE3
-rw-r--r--   1 BPXROOT  OMVSGRP       12 Jul 29 01:35 file1
-rw-r--r--   1 BPXROOT  OMVSGRP       12 Jul 29 01:35 file2
-rw-r--r--   1 BPXROOT  OMVSGRP       12 Jul 29 01:35 file3
./ansible/jcl@2022-07-29-08-35-02-bak:
total 38
drwxr-xr-x   2 BPXROOT  OMVSGRP     8192 Jul 29 01:35 .
drwxr-xr-x   4 BPXROOT  OMVSGRP     8192 Jul 29 02:40 ..
-rw-r--r--   1 BPXROOT  OMVSGRP       12 Jul 29 01:34 file1
-rw-r--r--   1 BPXROOT  OMVSGRP       12 Jul 29 01:34 file2
-rw-r--r--   1 BPXROOT  OMVSGRP       12 Jul 29 01:35 file3
./dest:
total 48
drwxr-xr-x   4 BPXROOT  OMVSGRP     8192 Jul 29 01:31 .
drwxrwxrwt   5 BPXROOT  OMVSGRP     8192 Jul 29 09:50 ..
drwxr-xr-x   2 BPXROOT  OMVSGRP        0 Jul 29 01:29 pat@2022-07-29-08-29-40-bak
drwxr-xr-x   2 BPXROOT  OMVSGRP     8192 Jul 29 01:31 path
./dest/pat@2022-07-29-08-29-40-bak:
total 16
drwxr-xr-x   2 BPXROOT  OMVSGRP        0 Jul 29 01:29 .
drwxr-xr-x   4 BPXROOT  OMVSGRP     8192 Jul 29 01:31 ..
./dest/path:
total 96
drwxr-xr-x   2 BPXROOT  OMVSGRP     8192 Jul 29 01:31 .
drwxr-xr-x   4 BPXROOT  OMVSGRP     8192 Jul 29 01:31 ..
-rw-r--r--   1 BPXROOT  OMVSGRP      240 Jul 29 01:31 ENCODE#D
-rw-r--r--   1 BPXROOT  OMVSGRP      240 Jul 29 01:31 ENCODE1
-rw-r--r--   1 BPXROOT  OMVSGRP      240 Jul 29 01:31 ENCODE2
-rw-r--r--   1 BPXROOT  OMVSGRP      240 Jul 29 01:31 TEST
./src:
total 32
drwxr-xr-x   2 BPXROOT  OMVSGRP     8192 Jul 29 01:31 .
drwxrwxrwt   5 BPXROOT  OMVSGRP     8192 Jul 29 09:50 ..

After executing the updated test cases from this branch you would get: 
bash-4.3# ls -l tmp
total 0

### CODE REVIEW

**Comment by fernandofloresg** [comment]
Screenshot 2022-08-08 at 10 45 21
Screenshot 2022-08-08 at 10 45 43

**Review by richp405 — APPROVED** [review]
This shows a good, legit use for the 'finally' clause.  It looks like all the blocks were copied faithfully.  Nice!

**Comment by fernandofloresg** [comment]
Screenshot 2022-08-17 at 15 11 56
Screenshot 2022-08-17 at 15 12 11
With latest changes.

**Review by richp405 — APPROVED** [review]
Still looks good

**Comment by ddimatos** [comment]
image
Internal [link/log](http://sprinkles1.fyre.ibm.com:8080/job/zosAnsible/1111/consoleText) for regression.

**Comment by ddimatos** [comment]
I did change the expected changed value from False to True for test `test_uss_encoding_conversion_when_dest_not_exists_01` , i looked over the code and could not see how it could ever be false, the nature of the iconv command alone needs to output to a temp file, the file `none` left behind as well.

**Pull request merged**
