### PR TITLE
Content/58/update documentation for release

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY
- Update all RST and MD files that populate the webdocs to reflect the latest upcoming release and its dependencies. 

- Update the zos_encode.py module short description to fit within the limits of the generated html for 'read-the-docs-plugin'

- Update the Make file so its shortcut is more generic and not seem that it will only work for IBM z/OS core collections, remove 'ibm_zos_core" with 'ibm_zos_doc'.

Bugfixes:
https://jsw.ibm.com/browse/NAZARE-782 - allow for user configuration and control the target and data set scratch directories
https://jsw.ibm.com/browse/NAZARE-1077 - doc bug semi colon over colon in path
https://jsw.ibm.com/browse/NAZARE-1081 - JCL and documentation updates to reflect necessary and option changes need in the playbook and JCL submitted by the the playbook.
https://jsw.ibm.com/browse/NAZARE-1080 - documentation around advanced inventory and ansible.cfg (ie, port and target tmp dirs)

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by blakeinate** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 rstcheck issue(s) which need to be resolved:
ERROR: docs/source/release_notes.rst:9:0: Title underline too short.
ERROR: The 1 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by ddimatos** [comment]
@blakeinate - note this is a draft review, i noticed a few more doc bugs in JIRA i can add to this PR.
@RadhaV2020 - FYI , upcoming doc changes I am making.

**Comment by blakeinate** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 2 rstcheck issue(s) which need to be resolved:
ERROR: docs/source/index.rst:23:0: Explicit markup ends without a blank line; unexpected unindent.
ERROR: docs/source/playbooks.rst:112:0: Unknown target name: "behavioral inventory parameters".
ERROR: The 1 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by blakeinate** [comment]
Exception: One or more pytest testcases failed! 
 ============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.0, py-1.8.1, pluggy-0.13.1
ansible: 2.9.6
rootdir: /var/lib/jenkins/workspace/zos-ansible-2/ibm_zos_core/tests
plugins: ansible-2.2.2, mock-1.12.1
collected 230 items

functional/module_utils/test_arg_parser.py ............................. [ 12%]
..............................................................           [ 39%]
functional/modules/test_zos_data_set_func.py F.......................... [ 51%]
.........................                                                [ 62%]
functional/modules/test_zos_fetch_func.py ........................       [ 72%]
functional/modules/test_zos_job_output_func.py ..                        [ 73%]
functional/modules/test_zos_job_query_func.py .                          [ 73%]
functional/modules/test_zos_job_submit_func.py ...                       [ 75%]
functional/modules/test_zos_operator_action_query_func.py .............. [ 81%]
............                                                             [ 86%]
functional/modules/test_zos_operator_func.py ......                      [ 89%]
functional/modules/test_zos_ping_func.py .                               [ 89%]
functional/modules/test_zos_tso_command_func.py ..........               [ 93%]
unit/test_zos_operator_action_query_unit.py .........                    [ 97%]
unit/test_zos_operator_unit.py .....                                     [100%]

=================================== FAILURES ===================================
_ test_data_set_catalog_and_uncatalog[\n//CREPDS    JOB (T043JM,JM00,1,0,0,0),'CREATE PDS',CLASS=R,\n//             MSGCLASS=X,MSGLEVEL=1,NOTIFY=OMVSADM\n//STEP1    EXEC PGM=IDCAMS\n//SYSPRINT DD  SYSOUT=A\n//SYSIN    DD   *\n     ALLOC -\n           DSNAME('USER.PRIVATE.TESTDS') -\n           NEW -\n           VOL(000000) -\n           DSNTYPE(PDS)\n/*\n] _

ansible_zos_module = <pytest_ansible.host_manager.v28.HostManagerV28 object at 0x7f3ee16b62d0>
jcl = "\n//CREPDS    JOB (T043JM,JM00,1,0,0,0),'CREATE PDS',CLASS=R,\n//             MSGCLASS=X,MSGLEVEL=1,NOTIFY=OMVSADM\n/...n           DSNAME('USER.PRIVATE.TESTDS') -\n           NEW -\n           VOL(000000) -\n           DSNTYPE(PDS)\n/*\n"

    @pytest.mark.parametrize(
        "jcl",
        [PDS_CREATE_JCL, KSDS_CREATE_JCL, RRDS_CREATE_JCL, ESDS_CREATE_JCL, LDS_CREATE_JCL],
    )
    def test_data_set_catalog_and_uncatalog(ansible_zos_module, jcl):
        hosts = ansible_zos_module
        hosts.all.zos_data_set(
            name=DEFAULT_DATA_SET_NAME, state="cataloged", volume=DEFAULT_VOLUME
        )
        hosts.all.zos_data_set(name=DEFAULT_DATA_SET_NAME, state="absent")
        hosts.all.file(path=TEMP_PATH, state="directory")
        hosts.all.shell(cmd="echo {0} > {1}/SAMPLE".format(quote(jcl), TEMP_PATH))
        results = hosts.all.zos_job_submit(
            src=TEMP_PATH + "/SAMPLE", location="USS", wait=True
        )
        hosts.all.file(path=TEMP_PATH, state="absent")
        # verify data set creation was successful
        for result in results.contacted.values():
            assert result.get("jobs")[0].get("ret_code").get("msg_code") == "0000"
        # verify first uncatalog was performed
        results = hosts.all.zos_data_set(name=DEFAULT_DATA_SET_NAME, state="uncataloged")
        for result in results.contacted.values():
            assert result.get("changed") is True
        # verify second uncatalog shows uncatalog already performed
        results = hosts.all.zos_data_set(name=DEFAULT_DATA_SET_NAME, state="uncataloged")
        for result in results.contacted.values():
            assert result.get("changed") is False
        # recatalog the data set
        results = hosts.all.zos_data_set(
            name=DEFAULT_DATA_SET_NAME, state="cataloged", volume=DEFAULT_VOLUME
        )
        for result in results.contacted.values():
>           assert result.get("changed") is True
E           assert False is True
E            +  where False = <built-in method get of dict object at 0x7f3ee0773a50>('changed')
E            +    where <built-in method get of dict object at 0x7f3ee0773a50> = {'_ansible_no_log': False, 'changed': False, 'exception': '  File "/tmp/ansible_zos_data_set_payload_a2g7i2mf/ansible_...cation': {'module_args': {'batch': None, 'data_class': None, 'format': None, 'name': 'USER.PRIVATE.TESTDS', ...}}, ...}.get

functional/modules/test_zos_data_set_func.py:143: AssertionError
================== 1 failed, 229 passed in 993.30s (0:16:33) ===================

**Comment by blakeinate** [comment]
Everything looks good to me. Additions will be very helpful for new users. Thank you!

**Pull request merged**
