### PR TITLE
Initial commit for module zos_operator

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY
Initial commit for the zos_operator module.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
zos_operator module

### CODE REVIEW

**Comment by blakeinate** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 3 future-import-boilerplate issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: tests/functional/modules/test_zos_operator_func.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: tests/unit/test_zos_operator_unit.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: Found 1 import issue(s) on python 3.7 which need to be resolved:
ERROR: plugins/modules/zos_operator.py:91:0: traceback: ModuleNotFoundError: No module named 'zoautil_py'
ERROR: Found 1 metaclass-boilerplate issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:0:0: missing: __metaclass__ = type
ERROR: Found 40 pep8 issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:35:19: W291: trailing whitespace
ERROR: plugins/modules/zos_operator.py:71:99: W291: trailing whitespace
ERROR: plugins/modules/zos_operator.py:72:99: W291: trailing whitespace
ERROR: plugins/modules/zos_operator.py:73:99: W291: trailing whitespace
ERROR: plugins/modules/zos_operator.py:78:17: W291: trailing whitespace
ERROR: plugins/modules/zos_operator.py:79:100: W291: trailing whitespace
ERROR: plugins/modules/zos_operator.py:81:61: W291: trailing whitespace
ERROR: plugins/modules/zos_operator.py:94:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/zos_operator.py:97:33: E231: missing whitespace after ','
ERROR: plugins/modules/zos_operator.py:123:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/zos_operator.py:124:13: E225: missing whitespace around operator
ERROR: plugins/modules/zos_operator.py:125:12: E251: unexpected spaces around keyword / parameter equals
ERROR: plugins/modules/zos_operator.py:125:14: E251: unexpected spaces around keyword / parameter equals
ERROR: plugins/modules/zos_operator.py:142:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/zos_operator.py:147:45: E231: missing whitespace after ','
ERROR: plugins/modules/zos_operator.py:147:48: E231: missing whitespace after ','
ERROR: plugins/modules/zos_operator.py:147:56: E231: missing whitespace after ','
ERROR: plugins/modules/zos_operator.py:151:39: E231: missing whitespace after ','
ERROR: plugins/modules/zos_operator.py:154:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/zos_operator.py:157:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/zos_operator.py:158:27: E231: missing whitespace after ','
ERROR: plugins/modules/zos_operator.py:159:113: E231: missing whitespace after ','
ERROR: plugins/modules/zos_operator.py:165:1: E305: expected 2 blank lines after class or function definition, found 1
ERROR: tests/functional/modules/test_zos_operator_func.py:23:34: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/test_zos_operator_func.py:24:34: E711: comparison to None should be 'if cond is not None:'
ERROR: tests/functional/modules/test_zos_operator_func.py:25:1: W293: blank line contains whitespace
ERROR: tests/functional/modules/test_zos_operator_func.py:26:1: E302: expected 2 blank lines, found 1
ERROR: tests/functional/modules/test_zos_operator_func.py:31:34: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/test_zos_operator_func.py:32:34: E711: comparison to None should be 'if cond is not None:'
ERROR: tests/functional/modules/test_zos_operator_func.py:34:1: E302: expected 2 blank lines, found 1
ERROR: tests/functional/modules/test_zos_operator_func.py:39:34: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/test_zos_operator_func.py:40:34: E711: comparison to None should be 'if cond is not None:'
ERROR: tests/functional/modules/test_zos_operator_func.py:42:1: E302: expected 2 blank lines, found 1
ERROR: tests/functional/modules/test_zos_operator_func.py:47:34: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/test_zos_operator_func.py:48:34: E711: comparison to None should be 'if cond is not None:'
ERROR: tests/unit/test_zos_operator_unit.py:61:1: E302: expected 2 blank lines, found 1
ERROR: tests/unit/test_zos_operator_unit.py:62:53: E231: missing whitespace after ','
ERROR: tests/unit/test_zos_operator_unit.py:69:11: E111: indentation is not a multiple of four
ERROR: tests/unit/test_zos_operator_unit.py:69:11: E117: over-indented
ERROR: tests/unit/test_zos_operator_unit.py:70:30: W292: no newline at end of file
ERROR: Found 20 pylint issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:97:32: bad-whitespace: Exactly one space required after comma         verbose=dict(type='bool',default=False),                                 ^
ERROR: plugins/modules/zos_operator.py:124:12: bad-whitespace: Exactly one space required around assignment     arg_defs=dict(             ^
ERROR: plugins/modules/zos_operator.py:125:12: bad-whitespace: No space allowed around keyword argument assignment         cmd = dict(             ^
ERROR: plugins/modules/zos_operator.py:147:44: bad-whitespace: Exactly one space required after comma     rc_message = OperatorCmd.execute(command,"",verbose,debug)                                             ^
ERROR: plugins/modules/zos_operator.py:147:47: bad-whitespace: Exactly one space required after comma     rc_message = OperatorCmd.execute(command,"",verbose,debug)                                                ^
ERROR: plugins/modules/zos_operator.py:147:55: bad-whitespace: Exactly one space required after comma     rc_message = OperatorCmd.execute(command,"",verbose,debug)                                                        ^
ERROR: plugins/modules/zos_operator.py:151:38: bad-whitespace: Exactly one space required after comma         raise OperatorCmdError(command,message.split('\n') if message else message)                                       ^
ERROR: plugins/modules/zos_operator.py:158:26: bad-whitespace: Exactly one space required after comma     def __init__(self, cmd,message):                           ^
ERROR: plugins/modules/zos_operator.py:159:112: bad-whitespace: Exactly one space required after comma         self.msg = 'An error occurred during issue the operator command "{0}", the response is "{1}"'.format(cmd,message)                                                                                                                 ^
ERROR: tests/functional/modules/test_zos_operator_func.py:23:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/test_zos_operator_func.py:24:15: singleton-comparison: Comparison to None should be 'expr is not None'
ERROR: tests/functional/modules/test_zos_operator_func.py:25:0: trailing-whitespace: Trailing whitespace
ERROR: tests/functional/modules/test_zos_operator_func.py:31:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/test_zos_operator_func.py:32:15: singleton-comparison: Comparison to None should be 'expr is not None'
ERROR: tests/functional/modules/test_zos_operator_func.py:39:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/test_zos_operator_func.py:40:15: singleton-comparison: Comparison to None should be 'expr is not None'
ERROR: tests/functional/modules/test_zos_operator_func.py:47:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/test_zos_operator_func.py:48:15: singleton-comparison: Comparison to None should be 'expr is not None'
ERROR: tests/unit/test_zos_operator_unit.py:62:52: bad-whitespace: Exactly one space required after comma def test_zos_opreator_various_args(zos_import_mocker,args, expected):                                                     ^
ERROR: tests/unit/test_zos_operator_unit.py:70:0: missing-final-newline: Final newline missing
ERROR: Found 6 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'No module named 'zoautil_py''
ERROR: plugins/modules/zos_operator.py:0:0: invalid-documentation: DOCUMENTATION.author: Invalid author for dictionary value @ data['author']. Got 'Ping Xiao <xiaoping@cn.ibm.com>'
ERROR: plugins/modules/zos_operator.py:0:0: invalid-documentation: DOCUMENTATION.short_description: required key not provided @ data['short_description']. Got None
ERROR: plugins/modules/zos_operator.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_operator.py:0:0: missing-python-interpreter: Interpreter line is not "#!/usr/bin/python"
ERROR: plugins/modules/zos_operator.py:81:13: return-syntax-error: RETURN is not valid YAML
ERROR: Found 1 yamllint issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:81:13: error: RETURN: syntax error: could not find expected ':' (syntax)
ERROR: The 7 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by blakeinate** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 24 pep8 issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:141:12: E251: unexpected spaces around keyword / parameter equals
ERROR: plugins/modules/zos_operator.py:141:14: E251: unexpected spaces around keyword / parameter equals
ERROR: plugins/modules/zos_operator.py:168:39: E231: missing whitespace after ','
ERROR: plugins/modules/zos_operator.py:175:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/zos_operator.py:176:27: E231: missing whitespace after ','
ERROR: plugins/modules/zos_operator.py:177:113: E231: missing whitespace after ','
ERROR: plugins/modules/zos_operator.py:183:1: E305: expected 2 blank lines after class or function definition, found 1
ERROR: tests/functional/modules/test_zos_operator_func.py:25:34: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/test_zos_operator_func.py:26:34: E711: comparison to None should be 'if cond is not None:'
ERROR: tests/functional/modules/test_zos_operator_func.py:27:1: W293: blank line contains whitespace
ERROR: tests/functional/modules/test_zos_operator_func.py:28:1: E302: expected 2 blank lines, found 1
ERROR: tests/functional/modules/test_zos_operator_func.py:33:34: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/test_zos_operator_func.py:34:34: E711: comparison to None should be 'if cond is not None:'
ERROR: tests/functional/modules/test_zos_operator_func.py:36:1: E302: expected 2 blank lines, found 1
ERROR: tests/functional/modules/test_zos_operator_func.py:41:34: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/test_zos_operator_func.py:42:34: E711: comparison to None should be 'if cond is not None:'
ERROR: tests/functional/modules/test_zos_operator_func.py:44:1: E302: expected 2 blank lines, found 1
ERROR: tests/functional/modules/test_zos_operator_func.py:49:34: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/test_zos_operator_func.py:50:34: E711: comparison to None should be 'if cond is not None:'
ERROR: tests/unit/test_zos_operator_unit.py:61:1: E302: expected 2 blank lines, found 1
ERROR: tests/unit/test_zos_operator_unit.py:62:53: E231: missing whitespace after ','
ERROR: tests/unit/test_zos_operator_unit.py:69:11: E111: indentation is not a multiple of four
ERROR: tests/unit/test_zos_operator_unit.py:69:11: E117: over-indented
ERROR: tests/unit/test_zos_operator_unit.py:70:30: W292: no newline at end of file
ERROR: Found 15 pylint issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:141:12: bad-whitespace: No space allowed around keyword argument assignment         cmd = dict(             ^
ERROR: plugins/modules/zos_operator.py:168:38: bad-whitespace: Exactly one space required after comma         raise OperatorCmdError(command,message.split('\n') if message else message)                                       ^
ERROR: plugins/modules/zos_operator.py:176:26: bad-whitespace: Exactly one space required after comma     def __init__(self, cmd,message):                           ^
ERROR: plugins/modules/zos_operator.py:177:112: bad-whitespace: Exactly one space required after comma         self.msg = 'An error occurred during issue the operator command "{0}", the response is "{1}"'.format(cmd,message)                                                                                                                 ^
ERROR: tests/functional/modules/test_zos_operator_func.py:25:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/test_zos_operator_func.py:26:15: singleton-comparison: Comparison to None should be 'expr is not None'
ERROR: tests/functional/modules/test_zos_operator_func.py:27:0: trailing-whitespace: Trailing whitespace
ERROR: tests/functional/modules/test_zos_operator_func.py:33:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/test_zos_operator_func.py:34:15: singleton-comparison: Comparison to None should be 'expr is not None'
ERROR: tests/functional/modules/test_zos_operator_func.py:41:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/test_zos_operator_func.py:42:15: singleton-comparison: Comparison to None should be 'expr is not None'
ERROR: tests/functional/modules/test_zos_operator_func.py:49:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/test_zos_operator_func.py:50:15: singleton-comparison: Comparison to None should be 'expr is not None'
ERROR: tests/unit/test_zos_operator_unit.py:62:52: bad-whitespace: Exactly one space required after comma def test_zos_opreator_various_args(zos_import_mocker,args, expected):                                                     ^
ERROR: tests/unit/test_zos_operator_unit.py:70:0: missing-final-newline: Final newline missing
ERROR: Found 3 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:0:0: missing-python-interpreter: Interpreter line is not "#!/usr/bin/python"
ERROR: plugins/modules/zos_operator.py:0:0: return-syntax-error: RETURN.result.type: not a valid value for dictionary value @ data['result']['type']. Got 'list[dict]'
ERROR: plugins/modules/zos_operator.py:55:15: invalid-examples: EXAMPLES is not valid YAML
ERROR: Found 1 yamllint issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:55:15: error: EXAMPLES: syntax error: could not find expected ':' (syntax)
ERROR: The 4 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by blakeinate** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 2 pep8 issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:180:113: E231: missing whitespace after ','
ERROR: tests/functional/modules/test_zos_operator_func.py:54:1: W391: blank line at end of file
ERROR: Found 2 pylint issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:180:112: bad-whitespace: Exactly one space required after comma         self.msg = 'An error occurred during issue the operator command "{0}", the response is "{1}"'.format(cmd,message)                                                                                                                 ^
ERROR: tests/functional/modules/test_zos_operator_func.py:54:0: trailing-newlines: Trailing newlines
ERROR: Found 2 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:0:0: missing-python-interpreter: Interpreter line is not "#!/usr/bin/python"
ERROR: plugins/modules/zos_operator.py:50:3: invalid-examples: EXAMPLES is not valid YAML
ERROR: Found 1 yamllint issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:50:3: error: EXAMPLES: syntax error: could not find expected ':' (syntax)
ERROR: The 4 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by blakeinate** [comment]
Exception: One or more pytest testcases failed! 
 ============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.0, py-1.8.1, pluggy-0.13.1
ansible: 2.9.6
rootdir: /var/lib/jenkins/workspace/zos-ansible-2/ibm_zos_core/tests
plugins: ansible-2.2.2, mock-1.12.1
collected 120 items

functional/module_utils/test_arg_parser.py ............................. [ 24%]
.......................                                                  [ 43%]
functional/modules/test_zos_data_set_func.py ........................... [ 65%]
.........................                                                [ 86%]
functional/modules/test_zos_job_output_func.py ..                        [ 88%]
functional/modules/test_zos_job_query_func.py .                          [ 89%]
functional/modules/test_zos_job_submit_func.py ...                       [ 91%]
functional/modules/test_zos_operator_func.py ....                        [ 95%]
functional/modules/test_zos_ping_func.py .                               [ 95%]
unit/test_zos_operator_unit.py FFFFF                                     [100%]

=================================== FAILURES ===================================
_________________ test_zos_opreator_various_args[args0-False] __________________

zos_import_mocker = (<pytest_mock.plugin.MockFixture object at 0x7f431a6b78d0>, <function zos_import_mocker.<locals>.perform_imports at 0x7f431a59b3b0>)
args = {'debug': True, 'verbose': False}, expected = False

    @pytest.mark.parametrize("args,expected", test_data)
    def test_zos_opreator_various_args(zos_import_mocker, args, expected):
        mocker, importer = zos_import_mocker
>       zos_operator = importer(IMPORT_NAME)

unit/test_zos_operator_unit.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
conftest.py:70: in perform_imports
    newimp = importlib.import_module(imports)
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'ansible_collections_ibm_zos_core'
import_ = <function _gcd_import at 0x7f431ed67b00>

>   ???
E   ModuleNotFoundError: No module named 'ansible_collections_ibm_zos_core'

<frozen importlib._bootstrap>:965: ModuleNotFoundError
_________________ test_zos_opreator_various_args[args1-False] __________________

zos_import_mocker = (<pytest_mock.plugin.MockFixture object at 0x7f431a5b9ad0>, <function zos_import_mocker.<locals>.perform_imports at 0x7f431a59b4d0>)
args = {'cmd': 123, 'debug': False, 'verbose': True}, expected = False

    @pytest.mark.parametrize("args,expected", test_data)
    def test_zos_opreator_various_args(zos_import_mocker, args, expected):
        mocker, importer = zos_import_mocker
>       zos_operator = importer(IMPORT_NAME)

unit/test_zos_operator_unit.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
conftest.py:70: in perform_imports
    newimp = importlib.import_module(imports)
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'ansible_collections_ibm_zos_core'
import_ = <function _gcd_import at 0x7f431ed67b00>

>   ???
E   ModuleNotFoundError: No module named 'ansible_collections_ibm_zos_core'

<frozen importlib._bootstrap>:965: ModuleNotFoundError
__________________ test_zos_opreator_various_args[args2-True] __________________

zos_import_mocker = (<pytest_mock.plugin.MockFixture object at 0x7f431a547a10>, <function zos_import_mocker.<locals>.perform_imports at 0x7f431a59b680>)
args = {'cmd': 'd u,all'}, expected = True

    @pytest.mark.parametrize("args,expected", test_data)
    def test_zos_opreator_various_args(zos_import_mocker, args, expected):
        mocker, importer = zos_import_mocker
>       zos_operator = importer(IMPORT_NAME)

unit/test_zos_operator_unit.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
conftest.py:70: in perform_imports
    newimp = importlib.import_module(imports)
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'ansible_collections_ibm_zos_core'
import_ = <function _gcd_import at 0x7f431ed67b00>

>   ???
E   ModuleNotFoundError: No module named 'ansible_collections_ibm_zos_core'

<frozen importlib._bootstrap>:965: ModuleNotFoundError
__________________ test_zos_opreator_various_args[args3-True] __________________

zos_import_mocker = (<pytest_mock.plugin.MockFixture object at 0x7f431a723cd0>, <function zos_import_mocker.<locals>.perform_imports at 0x7f431a59b560>)
args = {'cmd': 'd u,all', 'verbose': True}, expected = True

    @pytest.mark.parametrize("args,expected", test_data)
    def test_zos_opreator_various_args(zos_import_mocker, args, expected):
        mocker, importer = zos_import_mocker
>       zos_operator = importer(IMPORT_NAME)

unit/test_zos_operator_unit.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
conftest.py:70: in perform_imports
    newimp = importlib.import_module(imports)
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'ansible_collections_ibm_zos_core'
import_ = <function _gcd_import at 0x7f431ed67b00>

>   ???
E   ModuleNotFoundError: No module named 'ansible_collections_ibm_zos_core'

<frozen importlib._bootstrap>:965: ModuleNotFoundError
_________________ test_zos_opreator_various_args[args4-False] __________________

zos_import_mocker = (<pytest_mock.plugin.MockFixture object at 0x7f431a542810>, <function zos_import_mocker.<locals>.perform_imports at 0x7f431a59b5f0>)
args = {'cmd': 'd u,all', 'debug': 123}, expected = False

    @pytest.mark.parametrize("args,expected", test_data)
    def test_zos_opreator_various_args(zos_import_mocker, args, expected):
        mocker, importer = zos_import_mocker
>       zos_operator = importer(IMPORT_NAME)

unit/test_zos_operator_unit.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
conftest.py:70: in perform_imports
    newimp = importlib.import_module(imports)
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'ansible_collections_ibm_zos_core'
import_ = <function _gcd_import at 0x7f431ed67b00>

>   ???
E   ModuleNotFoundError: No module named 'ansible_collections_ibm_zos_core'

<frozen importlib._bootstrap>:965: ModuleNotFoundError
================== 5 failed, 115 passed in 525.26s (0:08:45) ===================

**Comment by blakeinate** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 9 pep8 issue(s) which need to be resolved:
ERROR: tests/functional/modules/test_zos_operator_func.py:21:13: E126: continuation line over-indented for hanging indent
ERROR: tests/functional/modules/test_zos_operator_func.py:23:21: E231: missing whitespace after ','
ERROR: tests/functional/modules/test_zos_operator_func.py:23:23: E231: missing whitespace after ','
ERROR: tests/functional/modules/test_zos_operator_func.py:24:25: E231: missing whitespace after ','
ERROR: tests/functional/modules/test_zos_operator_func.py:24:27: E231: missing whitespace after ','
ERROR: tests/functional/modules/test_zos_operator_func.py:25:37: E231: missing whitespace after ','
ERROR: tests/functional/modules/test_zos_operator_func.py:25:39: E231: missing whitespace after ','
ERROR: tests/functional/modules/test_zos_operator_func.py:26:13: E123: closing bracket does not match indentation of opening bracket's line
ERROR: tests/functional/modules/test_zos_operator_func.py:28:13: E117: over-indented
ERROR: Found 6 pylint issue(s) which need to be resolved:
ERROR: tests/functional/modules/test_zos_operator_func.py:23:20: bad-whitespace: Exactly one space required after comma             ("d r,l",0,True),                     ^
ERROR: tests/functional/modules/test_zos_operator_func.py:23:22: bad-whitespace: Exactly one space required after comma             ("d r,l",0,True),                       ^
ERROR: tests/functional/modules/test_zos_operator_func.py:24:24: bad-whitespace: Exactly one space required after comma             ("d parmlib",0,True),                         ^
ERROR: tests/functional/modules/test_zos_operator_func.py:24:26: bad-whitespace: Exactly one space required after comma             ("d parmlib",0,True),                           ^
ERROR: tests/functional/modules/test_zos_operator_func.py:25:36: bad-whitespace: Exactly one space required after comma             ("SEND 'list ready',NOW",0,True),                                     ^
ERROR: tests/functional/modules/test_zos_operator_func.py:25:38: bad-whitespace: Exactly one space required after comma             ("SEND 'list ready',NOW",0,True),                                       ^
ERROR: The 2 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by blakeinate** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 compile issue(s) on python 3.7 which need to be resolved:
ERROR: tests/functional/modules/test_zos_operator_func.py:34:14: SyntaxError: assert result['rc'] == expected_rc
ERROR: Found 5 pep8 issue(s) which need to be resolved:
ERROR: tests/functional/modules/test_zos_operator_func.py:21:26: W291: trailing whitespace
ERROR: tests/functional/modules/test_zos_operator_func.py:22:26: W291: trailing whitespace
ERROR: tests/functional/modules/test_zos_operator_func.py:23:28: W291: trailing whitespace
ERROR: tests/functional/modules/test_zos_operator_func.py:26:9: E123: closing bracket does not match indentation of opening bracket's line
ERROR: tests/functional/modules/test_zos_operator_func.py:34:9: E112: expected an indented block
ERROR: Found 1 pylint issue(s) which need to be resolved:
ERROR: tests/functional/modules/test_zos_operator_func.py:34:0: syntax-error: invalid syntax (&lt;unknown&gt;, line 34)
ERROR: The 3 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by xiaoping8385** [comment]
close and re-open to trigger pipeline

**Comment by blakeinate** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/zos_operator.py:0:0: return-syntax-error: RETURN.content.type: not a valid value for dictionary value @ data['content']['type']. Got 'list[str]'
ERROR: The 1 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by ddimatos** [comment]
Thanks for the code review @blakeinate and thank you @xiaopingBJ for the `zos_operator` module and working through the code reviews.

**Pull request merged**
