### PR TITLE
[Enabler] [zos_find] Test suite portability changes

### LINKED ISSUE #1593: [Enabler] [zos_find] Ensure test suite portability by removing hard coded data.
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

There is one test that looks for a data set older than 2 days of age patterns=['IMSTESTL.IMS01.RESTART', 'IMSTESTL.IMS01.LGMSGL'], uses IMSTESTL, I think this could be replaced for a system data set SYS1.something…

Many data set names are hardcoded, that is no a big problem because they get created and deleted each time the test runs, but those don’t have the ANSIBLE HLQ used across the suite, I recommend updating them.

### Ansible module

zos_find

### PR DESCRIPTION
**Pull request by rexemin**
##### SUMMARY
Fixes #1593.

##### ISSUE TYPE
- Enabler Pull Request

##### COMPONENT NAME
zos_find

### CODE REVIEW

**Review by ddimatos — CHANGES_REQUESTED** [review]
Can you do anything with the 2 volume entries both hard coded to 000000? If not, let me know so I can change the review status. 

I am thinking you should be able to use the volumes code Marcel created to choose a volume that is not hard coded.

**Comment by rexemin** [comment]
Screenshot 2024-08-14 at 9 45 07
Screenshot 2024-08-14 at 9 45 19

**Comment by rexemin** [comment]
Screenshot 2024-08-14 at 10 30 59
Screenshot 2024-08-14 at 10 31 10

**Comment by rexemin** [comment]
Thanks for catching that @ddimatos, I've changed the volumes used in those tests

**Review by ddimatos — APPROVED** [review]
Looks great @rexemin , thanks for working with me and addressing my comments.

**Review by fernandofloresg — APPROVED** [review]
LGTM!

**Pull request merged**
