### PR TITLE
[Enabler] [Various modules] Remove use of deprecated pipes library

### LINKED ISSUE #1327: [Enabler] [test_zos_data_set_func] Prepare for deprecation of pipes
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

In my testing, I noticed this error below, which is a pretty reasonable explanation that   

```
/Users/ddimatos/git/gh/ibm_zos_core/tests/functional/modules/test_zos_data_set_func.py:21: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
```
    
This results from an import `from pipes import quote`.

You can see `pipes` was removed in 3.13 
https://discuss.python.org/t/pep-594-has-been-implemented-python-3-13-removes-20-stdlib-modules/27124
and 
https://docs.python.org/3/library/pipes.html

It appears the code only uses is quote() which can be imported from shlex; `from shlex import quote`

See the pipes.py [here](https://github.com/python/cpython/blob/a3a0ce1b2ffb4f24be1587892aa89027382ea574/Lib/pipes.py#L66) import for quote

Seems to be present in several module utils as well as test cases. 

### Ansible module

_No response_

### PR DESCRIPTION
**Pull request by rexemin**
##### SUMMARY
Fixes #1327.

##### ISSUE TYPE
- Enabler Pull Request

##### COMPONENT NAME
- module_utils/backup.py
- module_utils/copy.py
- module_utils/encode.py
- zos_find
- zos_mvs_raw
- tests for zos_data_set

##### ADDITIONAL INFORMATION
Not only does it remove the use of `pipes` in zos_data_set tests, but it also removes the use throughout the entire collection.

### CODE REVIEW

**Comment by rexemin** [comment]
Pipeline results for half the modules affected.

Screenshot 2024-07-09 at 8 56 14
Screenshot 2024-07-09 at 8 56 26
Screenshot 2024-07-09 at 8 56 44

**Comment by rexemin** [comment]
Pipeline results for zos_copy

Screenshot 2024-07-09 at 16 09 28
Screenshot 2024-07-09 at 16 09 40
Screenshot 2024-07-09 at 16 10 00

**Comment by rexemin** [comment]
Screenshot 2024-07-09 at 12 16 48
Screenshot 2024-07-09 at 12 16 59
Screenshot 2024-07-09 at 12 17 12

**Review by fernandofloresg — APPROVED** [review]
Thanks a lot for this change!

**Review by ketankelkar — APPROVED** [review]
lgtm

**Comment by fernandofloresg** [comment]
Ivan is still running some tests so do not merge until Ivan says so

**Comment by rexemin** [comment]
And the pipeline results for the last two modules

Screenshot 2024-07-18 at 19 21 13
Screenshot 2024-07-18 at 19 21 22
Screenshot 2024-07-18 at 19 21 57

**Pull request merged**
