### PR TITLE
Bugfix/364/zos blockinfile backupname

### LINKED ISSUE #364: [Bug] [zos_blockinfile] Specifying backup_name causes an error
##### SUMMARY

When using module zos_blockinfile with option backup_name I receive this:
```
fatal: [lpar25]: FAILED! => changed=false 
  msg: Parameter verification failed
  stderr: Provided arg_type "backup_name" for argument "data_set_or_pat" is invalid.
  stderr_lines: <omitted>
```
Seems like the the problem is in `plugins/modules/zos_blockinfile.py` line 462, where `arg_type='data_set_or_pat'` should be `arg_type='data_set_or_path'` like on line 451. 

##### COMPONENT NAME

zos_blockinfile module

##### ANSIBLE VERSION

```
ansible [core 2.12.1]
  config file = /home/davidr/project/ansible/ansible.cfg
  configured module search path = ['/home/davidr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/davidr/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/davidr/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/davidr/.local/bin/ansible
  python version = 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
  jinja version = 3.1.2
  libyaml = True
```

##### SPECIFY ANSIBLE COLLECTION VERSION

1.4.0-beta.1

##### SPECIFY THE Z OPEN AUTOMATION UTILITIES VERSION

2021/08/05 22:12:58 CUT V1.2.0

##### ENVIRONMENT

z/OS v2.5

##### STEPS TO REPRODUCE

```yaml
- name: Update member
  zos_blockinfile:
    src: "CPAC.PARMLIB(BPXPRM00)"
    block: |
       MOUNT FILESYSTEM('SOME.DATA.SET') TYPE(ZFS) MODE(READ)
          MOUNTPOINT('/tmp/src/somedirectory')
    marker: "/* {mark} ANSIBLE MANAGED BLOCK */"
    backup: true
    backup_name: "CPAC.PARMLIB(BPXPRMBK)"
    state: present
```

##### EXPECTED RESULTS

A backup member is created and the specified member is updated.

##### ACTUAL RESULTS

```
Playbook output:
The full traceback is:
  File "/tmp/ansible_zos_blockinfile_payload_l0b0n6un/ansible_zos_blockinfile_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_blockinfile.py", line 406, in main
  File "/tmp/ansible_zos_blockinfile_payload_l0b0n6un/ansible_zos_blockinfile_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/better_arg_parser.py", line 787, in parse_args
    updated_value = handler.handle_arg()
  File "/tmp/ansible_zos_blockinfile_payload_l0b0n6un/ansible_zos_blockinfile_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/better_arg_parser.py", line 163, in handle_arg
    self.contents = self._resolve_arg_type()
  File "/tmp/ansible_zos_blockinfile_payload_l0b0n6un/ansible_zos_blockinfile_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/better_arg_parser.py", line 623, in _resolve_arg_type
    return self.type_handlers.get(self.arg_def.arg_type)(
  File "/tmp/ansible_zos_blockinfile_payload_l0b0n6un/ansible_zos_blockinfile_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/better_arg_parser.py", line 214, in _dict_type
    updated_value = handler.handle_arg()
  File "/tmp/ansible_zos_blockinfile_payload_l0b0n6un/ansible_zos_blockinfile_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/better_arg_parser.py", line 163, in handle_arg
    self.contents = self._resolve_arg_type()
  File "/tmp/ansible_zos_blockinfile_payload_l0b0n6un/ansible_zos_blockinfile_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/better_arg_parser.py", line 627, in _resolve_arg_type
    raise ValueError(
fatal: [lpar25]: FAILED! => changed=false 
  invocation:
    module_args:
      backup: true
      backup_name: CPAC.PARMLIB(BPXPRMBK)
      block: |-
       MOUNT FILESYSTEM('SOME.DATA.SET') TYPE(ZFS) MODE(READ)
          MOUNTPOINT('/tmp/src/somedirectory')
      encoding: IBM-1047
      insertafter: null
      insertbefore: null
      marker: /* {mark} ANSIBLE MANAGED BLOCK */
      marker_begin: BEGIN
      marker_end: END
      src: CPAC.PARMLIB(BPXPRM00)
      state: present
  msg: Parameter verification failed
  stderr: Provided arg_type "backup_name" for argument "data_set_or_pat" is invalid.
  stderr_lines: <omitted>

```

Thanks for the help!

### PR DESCRIPTION
**Pull request by fernandofloresg**
##### SUMMARY

This fixes a typo in the argument definition of backup name introduced recently. Also includes functional tests missing on backup name, checking both for USS and MVS datasets providing the backup name and leaving as None.

I propose to only check the content of USS file when backup_name is provided to avoid modifying the USSGeneral interface (Since it does its Job of comparing current content vs expected and cleans the tmp folder afterwards), either way the content of a USS backup is compared when backup_name is provided.

Also propose having a return clause on USSGeneral and DSGeneral helpers, to keep the zos_blockinfile result data available in case there are future tests cases where we need to execute further validations on it.

Fixes #364 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

zos_blockinfile
tests/functional/modules/test_zos_data_set_func.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by fernandofloresg** [comment]
Screenshot 2022-08-17 at 10 43 29
46a6e.png)

**Comment by fernandofloresg** [comment]
Added a clarification to the docs indicating that the MVS dataset provided in backup name should not be already allocated.

**Review by richp405 — APPROVED** [review]
nice work!

**Review by richp405 — APPROVED** [review]
I like the way you are keeping the result values separate.

**Review by ddimatos — APPROVED** [review]
The added test cases are great, perfect example of an issue that has a larger test effort that fix :) .

**Comment by ddimatos** [comment]
image

100% regression success, [link/log](http://sprinkles1.fyre.ibm.com:8080/job/zosAnsible/1119/consoleText)

**Comment by ddimatos** [comment]
Just an fyi, when I merged in `dev` it did not diff very well in that it did not show that you had changed the `backup_name=dict(arg_type='data_set_or_path', required=False, default=None),` even though I saw it in the initial review, such that it reverted it back to the typo. Anyhow, I added it back, if you feel you need to review once more that is fine, i will merge and we can open a new issue if needed. All the test cases passed so I assume my one merge issue is fine now.

**Pull request merged**
