### PR TITLE
enhancement/9108/zos_dataset_test_temp_files : Modify zos_data_set functional test suite to not leave tmp files

### PR DESCRIPTION
**Pull request by fernandofloresg**
##### SUMMARY

Modified path for temp JCL and added try- finally blocks to ensure cleanup in tests even in failures.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

tests/functional/modules/test_zos_data_set_func.py

Before this change executing `python3 -m pytest --ignore=functional/modules/test_module_security.py --durations=0 --host-pattern=all -Z=/var/lib/jenkins/workspace/zos-multipath-4/ibm_zos_core/configuration.yml ../tests/functional/modules/test_zos_data_set_func.py` would leave a folder called Ansible in /tmp.

```paste below
ls -l 

# ls -l tmp/
total 16
drwxr-xr-x   2 BPXROOT  OMVSGRP     8192 Aug  8 09:17 ansible

After it the leftover folder is no more.

ls -l 

# ls -l tmp/
total 0
```

### CODE REVIEW

**Comment by fernandofloresg** [comment]
Screenshot 2022-08-08 at 11 51 58

Branch parameters
Screenshot 2022-08-08 at 11 52 20

**Comment by fernandofloresg** [comment]
Screenshot 2022-08-09 at 15 53 59
Screenshot 2022-08-09 at 15 54 22

**Review by richp405 — APPROVED** [review]

**Review by richp405 — APPROVED** [review]
I don't see anything broken.   The tmp folder issue was a good catch!

**Review by ddimatos — APPROVED** [review]
Looks great, lots of nice updates and a clean system means less issues for other test suites.

**Comment by ddimatos** [comment]
I merged in dev to bring up some of the corrected PEP8 issues in other tests, ran clean
image

http://sprinkles1.fyre.ibm.com:8080/job/zosAnsible/1114/consoleText

**Pull request merged**
