### PR TITLE
[v1.10.0][zos_apf] Migrate zos_apf to ZOAU 1.3

### LINKED ISSUE #726: [Bug] [zos_apf] Test case occasionally fails
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_apf

### Enabler description

This is not a bug in Ansible Core's code but what I noticed is the occasional test case failure, I have raised this with ZOAU and looks like its going to be a 3Q work item thus we need to ensure we make time to validate. 

I think this is a timing issue, I think some where a data set is being listed maybe with `dls` and its taking to long or the code is non blocking thus moves on not waiting for the result of the data set to come back because this is intermittent.

There are many more details in zoau tracker: `9678`
Update: it might also be addressed by tracker `9679`.

Error:
```
    {'contacted': {'ec33017a.vmec.svl.ibm.com': {'_ansible_no_log': False,
    'changed': False,
    'invocation': {'module_args': {'batch': None,
                                   'force_dynamic': True,
                                   'library': 'APFTEST.P0000228.T0670444',
                                   'operation': None,
                                   'persistent': {'backup': False,
                                                  'backup_name': None,
                                                  'data_set_name': 'APFTEST.PRST.P6777445.T0562383',
                                                  'marker': '/* '
                                                            '{mark} '
                                                            'BLOCK '
                                                            '*/'},
                                   'sms': False,
                                   'state': 'present',
                                   'tmp_hlq': None,
                                   'volume': '000000'}},
    'rc': 8,
    'stderr': 'BGYSC4709E Was not '
              'able to find dataset '
              'APFTEST.P0000228.T0670444 '
              'in volume 000000.\n',
    'stderr_lines': ['BGYSC4709E Was '
                     'not able to '
                     'find dataset '
                     'APFTEST.P0000228.T0670444 '
                     'in volume '
                     '000000.'],
    'stdout': '',
    'stdout_lines': []}}
    }
```

I was able to recreate this in Python:
```
>>> from zoautil_py import zsystem, datasets
>>> opt='add'
>>> dsname='APFTEST.P0000228.T0670444'
>>> volume='000000'
>>> sms = False
>>> forceDynamic=True
>>> persist = {'addDataset': 'APFTEST.PRST.P6777445.T0562383', 'marker': "/* {mark} BLOCK */"}
>>> zsystem.apf(opt=opt, dsname=dsname, volume=volume, sms=sms, forceDynamic=forceDynamic, persistent=persist).stderr_response
'BGYSC4709E Was not able to find dataset APFTEST.P0000228.T0670444 in volume 000000.\n' 
```
Recreate Python error:
```
>>> zsystem.apf(opt=opt, dsname=dsname, volume=volume, sms=sms, forceDynamic=forceDynamic, persistent=persist).stderr_response
'BGYSC4709E Was not able to find dataset APFTEST.P0000228.T0670444 in volume 000000.\n' 
```

ISPF shows the Data set exists:
```
   Menu  Options  View  Utilities  Compilers  Help                    USRT001   
 ------------------------------------------------------------------------------ 
 DSLIST - Data Sets on volume 000000                   CHARS 'APFTEST.P0000228. 
 Command ===>                                                  Scroll ===> PAGE 
                                                                                
 Command - Enter "/" to select action                  Message           Volume 
 -------------------------------------------------------------------------------
          APFTEST.P0000228.T0670444                                      000000 
          APFTEST.P0000237.T0097937                                      000000 
          SYS23023.T100843.RA000.USRT001.R0100073                        000000 
          SYS23023.T100843.RA000.USRT001.R0100075                        000000 
          SYS23023.T100843.RA000.USRT001.SYSUT1.H01                      000000 
          TMPHLQ.P0331812.T0592613.C0000000                              000000 
 ***************************** End of Data Set list **************************** 
```

Data set attributes:
```
                              Data Set Information                    USRT001   
 Command ===>                                                                   
                                                                    More:     + 
 Data Set Name . . . . : APFTEST.P0000228.T0670444                              
                                                                                
 General Data                           Current Allocation                      
  Management class . . : **None**        Allocated tracks  . : 100              
  Storage class  . . . : **None**        Allocated extents . : 1                
   Volume serial . . . : 000000                                                 
   Device type . . . . : 3390                                                   
  Data class . . . . . : **None**                                               
   Organization  . . . : PS             Current Utilization                     
   Record format . . . : FB              Used tracks . . . . : 0                
   Record length . . . : 80              Used extents  . . . : 0                
   Block size  . . . . : 27920                                                  
   1st extent tracks . : 100                                                    
   Secondary tracks  . : 100            Dates                                   
   Data set name type  :                 Creation date . . . : 2023/01/26       
   Data set encryption : NO              Referenced date . . : ***None***       
                                         Expiration date . . : ***None***       
                                                                                
   SMS Compressible  . : NO     
```

ZOAU shell command has no issues:
```
[ OMVSADM:/u/omvsadm: ]apfadm -l |grep APFTEST.PRST.P6777445.T0562383
                                           1570  000000 APFTEST.PRST.P6777445.T0562383
```
ZOAU shell command result:
```
apfadm -A APFTEST.PRST.P6777445.T0562383 -M "/* {mark} BLOCK */" -P "APFTEST.P0000228.T0670444"
EC33017A  2023026  22:37:10.98             ISF031I CONSOLE OMVSADM ACTIVATED
EC33017A  2023026  22:37:10.98            -SETPROG APF,ADD,DSNAME=APFTEST.PRST.P6777445.T0562383,VOLUME=000000
EC33017A  2023026  22:37:11.10             CSV410I DATA SET APFTEST.PRST.P6777445.T0562383 ON VOLUME 000000 ADDED TO APF LIST 
```

### LINKED ISSUE #1102: [Enabler] [Dev] [zos_apf] Migrate module, module utilities and test cases to ZOAU 1.3
## Ansible module
`zos_apf`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

With the adoption of ZOAU 1.3, modules, module utilities and test cases may need to be updated according to the [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier). 

#### APIs changes impacting module:
- Impacted by ZOAU Dataset API: No
- Impacted by ZOAU jobs API: No
- Impacted by the rename of types.py to ztypes.py: No
- Impacted by the contents of module volumes.py having been moved to datasets.py: No
- Impacted by opercmd timeout to milli seconds: No
- Impacted by JSON schema change in either apfadm, dmod, dsed or zinfo: Yes
   - Please see the notes below as the API affecting `apfadm` is internal to  zoautil_py's `zsystem.py` and not affecting this module.
- Impacted by Exceptions schema: No

#### This issue depends on shared import identified by git issues:
- [module_utils/better_arg_parser.py](https://github.com/ansible-collections/ibm_zos_core/issues/1116)
- [module_utils/data_set.py](https://github.com/ansible-collections/ibm_zos_core/issues/1118)
- [module_utils/backup.py](https://github.com/ansible-collections/ibm_zos_core/issues/1115)

#### Notes: 
After reviewing the modules source, it appears the module is not affected by the ZOAU AP changes, this should only need regression testing. This is because the module response only relies on 3 attributes and those did not change. Note, that the content for the `zoauresponse` has been encapsulated with a `data` object (#954), while I don't believe we return any content, validation should be covered through regression testing.

zoauresponse objects accessed:
```
    operOut = ret.stdout_response
    operErr = ret.stderr_response
    operRc = ret.rc
```
For reference the JSON Schema changes with examples should also be reviewed [here](https://www.ibm.com/docs/en/zoau/1.3.x?topic=examples-json-schema)

#### Related issues
#726 - `zos_apf` can be difficult to run with success and that success depends on this issue completing
#954 - we may cancel this issue if the work is handled on each module

### PR DESCRIPTION
**Pull request by fernandofloresg**
##### SUMMARY

There are four main changes in this PR:
- One is fixing a bug I discovered while testing. Apparently, APF with list option was only returning one data set, this is now fixed to return the complete list of data sets found.
 
- ZOAU 1.3 Migration changes: 
Updated the way a list of data sets is created to address new JSON "data" tag and how it returns when option operation  = 'list' to return the same expected output for this field and not break playbooks written with previous versions. 
 
- Enhancements 
Separated the json.loads clause and extended to catch all exceptions and throw a better error message.
Updated test cases to be in try - finally clause to properly remove data sets and files created even if the test failed. 

- Introduced a new fixture and function inside volumes.py
During testing I got errors that relate to #726 , now ZOAU has updated their error message and was clear about what the issue was. apf needs to check the VVDS for a volume, since the ECs get restored every week they keep deleting the VVDS, this is fixed by simply creating a new VSAM on that specific volume.
Created a function that will get the volumes that have a VVDS, if there are none it will try to create it in the supplied volumes.

Fixes #1102 
Fixes #726 
##### ISSUE TYPE

- Feature Pull Request
- 
##### COMPONENT NAME

zos_apf

### CODE REVIEW

**Comment by fernandofloresg** [comment]
Screenshot 2024-02-08 at 9 18 05 PM
 
Screenshot 2024-02-08 at 9 20 05 PM

**Comment by fernandofloresg** [comment]
Screenshot 2024-02-09 at 12 24 41 PM
Screenshot 2024-02-09 at 12 25 08 PM

**Review by richp405 — APPROVED** [review]
Looks okay from here

**Review by AndreMarcel99 — APPROVED** [review]
I love the changes for volumes, thanks

**Pull request merged**
