### PR TITLE
Removed emergency backup and auto-recovery features.

### PR DESCRIPTION
**Pull request by richp405**
##### SUMMARY
Removed 'emergency backup' feature and behavior from zos_copy

Addresses #696 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
zos_copy 
The module has a built-in emergency backup system, which is no longer needed.
The backup feature is unchanged, so backup=True or backup_name=(not none) will still trigger a backup
auto-winding/deletion of backup is also removed.

### CODE REVIEW

**Comment by richp405** [comment]
image

**Review by rexemin — APPROVED** [review]
Looks good, thanks for researching this issue!

**Review by ddimatos — APPROVED** [review]
This looks good to me, thanks @richp405 , ill put a comment in the main issue for Ivan to see.

**Comment by ddimatos** [comment]
@ivan, I will defer to you where we can do this now or a future update which is to remove the `erase_backup` and `restore_backup` from zos_copy and move into module_utils but likely we have logic for backup and restoring based on backup=true, backup_name=""

**Comment by richp405** [comment]
@ddimatos @rexemin: It looks trivial, since the code is now unused.  I can rebuild without them if you wish.  Just let me know

**Comment by rexemin** [comment]
I would like to see a rebuild without those functions, I think it's better to clean up the code if there are parts that are unused.

**Comment by richp405** [comment]
image
Only change was removing the 2 routines.  It passed build tests without issues.

**Comment by ddimatos** [comment]
Team decided to keep `erase_backup` and `restore_backup` as a possible reuse on a future option that would allow a recovery on module failure for the user.

**Pull request merged**
