### PR TITLE
Update make file with new features to manage the nodes

### PR DESCRIPTION
**Pull request by ddimatos**
Signed-off-by: ddimatos <dimatos@gmail.com>

##### SUMMARY
This addresses issue #562 

This is the last remaining desired feature for the makefile that expedites development routines. In this request support was added to the Makefile, make.env as well as include the mount-shr.sh and profile-shr files to the new scripts directory. Although the new content was encrypted, its not likely content we needed to encrypt. 

This change brings several new commands, most notably `mountProfile` which will copy the users key to the z/os node, also if that node is known to be a production server, will copy the Jenkins keys then copy and execute the mount-shr script for our supershare and lastly leave a profile behind in directory `/u/<user>`.

```
printMount:  Print the contents of the venv/mount-shr.sh, this only works if
            you have set up a venv using `make vsetup` because a password is required to
            decrypt and a decrypted copy will be placed in the venv.

printProfile:  Print the contents of the venv/profile-shr, this only works if
            you have set up a venv using `make vsetup` because a password is required to
            decrypt and a decrypted copy will be placed in the venv.

mountProfile:  Copy your ssh key to a `host` or the default which is your username. Then
            copy the super share mount script and profile for the mounts, execute the
            mount script and exit, upon rmote ssh, `profile-shr` will be located
            at `/u/${user} where user is defined in the make.env `host_list`. You must
            have set up a venv `venv` as that is where the environment script and configurations
            get written to manage this make file. It avoids continued decryption prompts to
            force users to set up the venv via `vsetup`
```

 Example output:
 ```
ddimatos:[ ~/git/github/ibm_zos_core ]make mountProfile host=xxxxxx
====================================================================
Copying SSH keys to the managed node authorized_keys.
====================================================================
====================================================================
Copying mount script to managed node and executing.
Copying profile-shr to managed node.
====================================================================
mount-shr.sh                                                                                                                                                                     100% 3362    32.1KB/s   00:00
profile-shr                                                                                                                                                                      100% 9426    91.4KB/s   00:00
unmounting /python
unmounting /python2
unmounting /python3
unmounting /allpython/3.10
remounting IMSTESTU.PYZ.ROCKET.V362B.ZFS
remounting IMSTESTU.PYZ.V380.GA.ZFS
remounting IMSTESTU.PYZ.V383PLUS.ZFS
remounting IMSTESTU.PYZ.V3A0.ZFS

Done
```

##### Complete make help output now
```
encrypt:    Encrypt the configuration files with a `.encrypt` suffix for files
            [make.env, mount-shr.sh, profile-shr] with user specified password.
            Example:
                $ make encrypt
            Note: This is not a common operation, unless you tend to edit the configuration, avoid using this feature.
decrypt:    Decrypt all scripts used with this Makefile using the user specified password
            Files include: ["mount-shr.sh", "profile-shr", "make.env"]
            Example:
                $ make decrypt
vsetup:     Create a python virtual environment (venv) based on the systems python3
            Options:
                req - a user provided requirements.txt, if this is not set one will be
                created for you.
            Example:
                $ make vsetup
                $ make vsetup req=tests/requirements.txt
vstart:     Start the venv if you plan to work in a python virtual environment
            Example:
                $ make vstart
vstop:      Deactivate (stop) the venv
            Example:
                $ make vstop
build:      Build and installa collection of the current branch checked out
            Example:
                $ make build
test:       Run collection functional tests inside the python virtual environment (venv)
            Options:
                host - z/OS managed node to run test cases, no selection will default to
                       a system registerd to your user name, see make.env
                python - IBM enterprise python version, choices are 3.8, 3.9, 3.10, 3.11
                         no selection defauls to 3.8
                zoau - Z Open Automation Utilites to use with the collection, choices are 1.0.3, 1.1.1, 1.2.0, 1.2.1
                       no selection defaults to 1.1.1
                name - the absoulte path to a particluar test case to run, no selection
                       will default to all test cases running.
                debug - enable debug for pytest (-s), any value will result in true enabling
                        debug, default is to not define a value so that it evaluates to false
            Example:
                $ make test (runs all tests using default users system and dependencies)
                $ make test name=tests/functional/modules/test_zos_copy_func.py debug=true (run specific test and debug)
                $ make test host=ec33012a python=3.9 zoau=1.1.1 name=tests/functional/modules/test_zos_copy_func.py debug=true
sanity:     Run sanity tests either in the virtual environment (venv) or docker if there is a running docker engine
            Options:
                version - choose from '2.6', '2.7', '3.5', '3.6', '3.7', '3.8', '3.9', no selection will run all available python versions
            Example:
                $ make sanity version=3.8
                $ make sanity
bandit:     Run a bandit security scan on the plugins directory, set the severity level.
            Options:
                level - choose from 'l', 'll', 'lll'
                      - l all low, medium, high severity
                      - ll all medium, high severity
                      - lll all hight severity
            Example:
                $ make bandit sev=ll
                $ make bandit sev=l
install:    Install a collection from galaxy and specify the version.
            Options:
                version - any GA and beta versions currently on Galaxy
            Example:
                $ make install 1.4.0-beta.1
                $ make install
version:    Get the version of the ibm_zos_core collection installed
            Example:
                $ make version
printConfig:  Print the contents of the config file (venv/config.yml) which is used to
            connect to the managed z/OS node to run functional tests on. This will only
            be available if yo have set up a venv using `make vsetup` because a password
            is required to generate the config and is considered sensitive content per
            corporate policy.
            Example:
                $ make printConfig
printEnv:   Print the contents of the venv/make.env, this only works if
            you have set up a venv using `make vsetup` because a password is required to
            decrypt and a decrypted copy will be placed in the venv.
            Example:
                $ make printEnv
printMount:  Print the contents of the venv/mount-shr.sh, this only works if
            you have set up a venv using `make vsetup` because a password is required to
            decrypt and a decrypted copy will be placed in the venv.
            Example:
                $ make printMount
printProfile:  Print the contents of the venv/profile-shr, this only works if
            you have set up a venv using `make vsetup` because a password is required to
            decrypt and a decrypted copy will be placed in the venv.
            Example:
                $ make printEnv
clean:      Cleanup and teardown the environment based on the level selected.
            Options:
                level - choose from 'min', 'all'
                      - 'all' will remove the venv, restore any temporarily located files
                        and ensure config is encrypted
                      - 'min' will restore any temporarily located files
                        and ensure config is encrypted
            Example:
                $ make clean level=all
                $ make clean level=min

                      Copy your ssh key to a `host` or the default which is your username. If you are
            copying a key to a production server, a second key will be copied used by the

copyKey:    have set up a venv `venv` as that is where the environment script and configurations
            get written to manage this make file. It avoids continued decryption prompts to
            force users to set up the venv via `vsetup`
            Options:
                host - choose from a known host or don't set a value for the default operation
                       which is to user your username to look up your default system
            Example:
                $ make copyKey host=ec33012a
                $ make copyKey
mountProfile:  Copy your ssh key to a `host` or the default which is your username. Then
            copy the super share mount script and profile for the mounts, execute the
            mount script and exit, upon rmote ssh, `profile-shr` will be located
            at `/u/${user} where user is defined in the make.env `host_list`. You must
            have set up a venv `venv` as that is where the environment script and configurations
            get written to manage this make file. It avoids continued decryption prompts to
            force users to set up the venv via `vsetup`
            Options:
                host - choose from a known host or don't set a value for the default operation
                       which is to user your username to look up your default system
            Example:
                $ make mountProfile host=ec33012a
                $ make mountProfile
printTargets:  Display the z/OS managed nodes available and configured. This will show which
            systems you can use in the host argument for `make test host<....>`
            Example:
                $ make printTargets
buildChglog:  Build the changelog, this should be a release activity otherwise the generated
            files should not be checked in.
            Example:
                $ make buildChglog
buildDoc:   Update the documentation for the collection after module doc changes have been
            made. This simply calls the make file in the docs directory, see the make file
            there for additional options.
            Example:
                $ make buildDoc
cleanDoc:   Cleanup and remove geneated doc for the collection if its not going to be
            checked in
            Example:
                $ make cleanDoc
help:       Help on how how to use this Makefile, options and examples.
```

### CODE REVIEW

**Comment by ddimatos** [comment]
@fernandofloresg when the review is completed please merge and delete the branch.
FYI @richp405 , you can use this now to key the z/OS ec as well as run the mount scripts. 

No regression is needed, this is an isolated file unrelated to Ansible modules

**Comment by ddimatos** [comment]
Given this update is unrelated to any shipped source and simply used to assist development with utilities that can simplify their daily tasks, this PR need not wait for a review.

**Comment by ddimatos** [comment]
Folks, this review is a formality, its more for you to look over the functionality the utility provides so you can ease your daily development tasks. This code is segregated and is not included in any product or production code thus quick review and approval is all that is needed.

**Review by fernandofloresg — APPROVED** [review]
LGTM

**Pull request merged**
