### PR TITLE
Enhance zos_archive and zos_unarchive test cases

### LINKED ISSUE #897: [Enhancement] [zos_archive, zos_unarchive] Simplify test cases
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_archive, zos_unarchive

### Enhancement or feature description

Before merging I identified test cases combinations are many and tested again and again because of record_format and record_length. Instead of testing in each case, better to isolate them into their own test cases.

### PR DESCRIPTION
**Pull request by fernandofloresg**
##### SUMMARY

Enhance the zos_archive and zos_unarchive, original idea was to simplify test cases but added test_lines with the actual record length of the dataset and take into account RDW.

Fixes #897 

##### ISSUE TYPE

- Enhancement Pull Request

### CODE REVIEW

**Comment by fernandofloresg** [comment]
Screenshot 2023-09-12 at 10 30 20 AM

**Review by AndreMarcel99 — APPROVED** [review]
Clean change, maybe the idea is take this changes and add test cases to exceed record length, and in a full capacity to see how archive and unarchive the content.

**Review by rexemin — APPROVED** [review]
Good call to use lines the size of the record length for these tests, looks good

**Comment by fernandofloresg** [comment]
Screenshot 2023-09-13 at 4 35 44 PM
With latest changes

**Pull request merged**
