### PR TITLE
Fixes for #664 and #678 for 1.4.1

### PR DESCRIPTION
**Pull request by rexemin**
##### SUMMARY
Fixes for both #664 and #678, but now for release 1.4.1. The same code found in PR #725.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zos_copy

### CODE REVIEW

**Review by ddimatos — APPROVED** [review]
LGTM, seen this before :)

**Review by ddimatos — CHANGES_REQUESTED** [review]
Waiting on

**Review by ddimatos — APPROVED** [review]
Looks good, thank you @rexemin

**Review by richp405 — APPROVED** [review]
looks okay to me

**Pull request merged**
