### PR TITLE
Enabler/992/resolve sanity four

### PR DESCRIPTION
**Pull request by richp405**
##### SUMMARY
This ticket is for the forward-part of the zos_data_set module for the new 1.3.0 development work.

Changes will resolving sanity test linting issues #992, #993, #994

(correction - had previously shown different lint issues: These three are all part of modules/zos_data_set.py)

Also corrected 'truthy' findings in the zos_data_set in-code documentation
('true' replacing 'Yes' in examples)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
zos_data_set

### CODE REVIEW

**Comment by ddimatos** [comment]
@richp405 can you confirm and update the description of this issue given our conversations that this PR is for #992 #993 and #994 . Thank you.

**Comment by richp405** [comment]
This PR is waiting on the staging-1.9 PR completing testing.

**Comment by richp405** [comment]
added #1191 for the 1.9 staging PR.

**Comment by richp405** [comment]
closing in favor of 1285

**Pull request closed without merging**
