### PR TITLE
Rename normaly.py to zos_ping.py

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY
Rename normal.py to zos_ping.py such that we address and adhere to this Ansible Change in this PR:https://github.com/ansible/ansible/pull/67684

Hoping this change will avoid having to set: ANSIBLE_ACTION_PLUGINS

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by blakeinate** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 action-plugin-docs issue(s) which need to be resolved:
ERROR: plugins/action/zos_ping.py:0:0: action plugin has no matching module to provide documentation
ERROR: Found 1 ignores issue(s) which need to be resolved:
ERROR: tests/sanity/ignore-2.9.txt:10:1: File 'plugins/action/normal.py' does not exist
ERROR: The 2 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by blakeinate** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 ignores issue(s) which need to be resolved:
ERROR: tests/sanity/ignore-2.9.txt:10:1: Line cannot be empty or contain only a comment
ERROR: The 1 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by blakeinate** [comment]
Duplicate to PR #77

**Comment by ddimatos** [comment]
Closing as a result of duplicate changes , see this PR for the same result and changes: https://github.com/ansible-collections/ibm_zos_core/pull/77

**Pull request closed without merging**
