### PR TITLE
Enhancement/3688b

### PR DESCRIPTION
**Pull request by richp405**
##### SUMMARY

This is a reload of 3688, using /dev instead of /master 1.2 as a starting   point:
  + Enhancement to zos_job_submit to pre-filter \r from local jcl jobs.
  + Enhancement to better_arg_parser to resolve local directory references.
  + Change to allow case-mismatches on choice arg types.

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by IBMAnsibleHelper** [comment]
Exception: script returned exit code 1

**Comment by ddimatos** [comment]
@richp405 - the issue is you built your changes on `master` , the commit how has that source, no matter what branch trickery you do, its not going away. Basically you can do a manual edit or 3 way merge, but given its pretty simple just copy/paste and test based off `dev` would work.

See your commit:
image

A 2 dot comparison puts `3668` and `3688b` equal:
image

Hit me up tomorrow if you want to talk more on this.

**Comment by IBMAnsibleHelper** [comment]
Exception: script returned exit code 1

**Comment by IBMAnsibleHelper** [comment]
Exception: script returned exit code 1

**Comment by IBMAnsibleHelper** [comment]
Exception: script returned exit code 1

**Comment by IBMAnsibleHelper** [comment]
Exception: script returned exit code 1

**Comment by IBMAnsibleHelper** [comment]
Exception: script returned exit code 1

**Comment by richp405** [comment]
Closing to re-pull dev and get this code up to date

**Pull request closed without merging**
