### PR TITLE
Release v1.2.0 beta.4

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY

Beta release to galaxy:

Version 1.2.0-beta.4
====================

Notes
-----

* Update recommended
* Bugfix

  * Fixes a bug for `zos_data_set` module where some parameters were not
    getting passed correctly because python considers integer value of 0
    to be false.
  * Fixes documentation in module `zos_job_submit` where **wait_time_s** should
    have been written as **duration_s**.
  * Fixes requirements version in sample playbook hosts-setup.yaml

* Module Changes

  * Module ``zos_copy`` can now use wildcards to copy multiple PDS/PDSE members
    to another PDS/PDSE

Availability
------------

* Galaxy
* GitHub

Reference
---------

* Supported by IBM Open Enterprise Python for z/OS: 3.8.2 or later
* Supported by IBM Z Open Automation Utilities 1.0.3 PTF UI70435
* Supported by z/OS V2R3
* The z/OS® shell

Known issues
------------

* Modules

  * When executing programs using ``zos_mvs_raw``, you may encounter errors
    that originate in the programs implementation. Two such known issues are
    noted below of which one has been addressed with an APAR.

    #. ``zos_mvs_raw`` module execution fails when invoking
       Database Image Copy 2 Utility or Database Recovery Utility in conjunction
       with FlashCopy or Fast Replication.
    #. ``zos_mvs_raw`` module execution fails when invoking DFSRRC00 with parm
       "UPB,PRECOMP", "UPB, POSTCOMP" or "UPB,PRECOMP,POSTCOMP". This issue is
       addressed by APAR PH28089.

##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by IBMAnsibleHelper** [comment]
Exception: script returned exit code 1

**Comment by IBMAnsibleHelper** [comment]
Exception: script returned exit code 1

**Comment by IBMAnsibleHelper** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 no-smart-quotes issue(s) which need to be resolved:
ERROR: docs/source/conf.py:183:11: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: Found 1 pep8 issue(s) which need to be resolved:
ERROR: docs/source/conf.py:184:18: W292: no newline at end of file
ERROR: Found 1 pylint issue(s) which need to be resolved:
ERROR: docs/source/conf.py:184:0: missing-final-newline: Final newline missing
ERROR: The 3 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Review by blakeinate — APPROVED** [review]
Looks great, thanks for putting this together @ddimatos !

**Pull request merged**
