### PR TITLE
Update meta data and docs for 1.5.0-beta.1 release tasks

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY
Addresses #390 , #630 , #649 , #651

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by ketankelkar — COMMENTED** [review]
CHANGELOG.rst 
- line 49, add a space after the dash
- line 70 - fixed should be fixes , also capitalize F
- line 76 - capitalize f in fixes

changelogs/changelog.yml
- line 388 - fixed should be fixes , also capitalize F
- line 407 - capitalize f in fixes
- line 409 - consider removing word ‘this’ and start sentence with “Also cleans up…”
- line 581 - 588-zos_copy-emergenxy-backup.yml should be emergency not emergenxy

for meta/runtime.yml
- are we still supoorting 2.9? should ansible-core version be bumped up?

**Comment by ddimatos** [comment]
> CHANGELOG.rst
> 
>     * line 49, add a space after the dash
> 
>     * line 70 - fixed should be fixes , also capitalize F
> 
>     * line 76 - capitalize f in fixes
> 
> 
> changelogs/changelog.yml
> 
>     * line 388 - fixed should be fixes , also capitalize F
> 
>     * line 407 - capitalize f in fixes
> 
>     * line 409 - consider removing word ‘this’ and start sentence with “Also cleans up…”
> 
>     * line 581 - 588-zos_copy-emergenxy-backup.yml should be emergency not emergenxy
> 
> 
> for meta/runtime.yml
> 
>     * are we still supoorting 2.9? should ansible-core version be bumped up?

Thanks @ketankelkar , ill make the edits although not keen on editing what was generated, those files you reference are generated based on our changelog fragments, this is why I commented when we get to the point they are where we like them to be we can drop the release_notes.rst, changelog fragments are a what feeds the tooling so spelling and other errors will come through. 

As for 2.9 , yes we are still supporting 2.9 through September 29th 2023, [we support it till AAP 1.2 goes out of service](https://access.redhat.com/support/policy/updates/ansible-automation-platform).

**Comment by ddimatos** [comment]
Also note I did not put a limit on the ansible version this time around because it will allow users to easily try the dev branch (ansible-core 2.15) , when we GA to Hub we can determine the upper bound at that time of what is required by RH.

**Comment by ddimatos** [comment]
Most the edits are in place, I can't change `line 581 - 588-zos_copy-emergenxy-backup.yml should be emergency not emergenxy` because those are the actual fragments and unfortunately are misspelled, we already removed those fragments from our history thus if i change them here I have no way to change them in the older branches.

**Review by ketankelkar — APPROVED** [review]
lgtm!

**Pull request merged**
