### PR TITLE
Bugfix/578/correct linting issues

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY
Fixes issue #578 and one additional lint issue that corrects a missing keyword from galaxy.yml (new requirement) that was included in v.1.3.6 but regressed in 1.4.0.

These changes should be propagated to the `dev` and `release-1.5.0-beta.1` branches as well if they aren't. 

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by ddimatos** [comment]
No need to forward port to release-v1.5.0-beta.1 branch, it is already present.
https://github.com/ansible-collections/ibm_zos_core/blob/0307b07505e5fbb16eccd34cd21b3b5a640458e2/plugins/modules/zos_job_query.py#L288

**Comment by ddimatos** [comment]
Job log suffix `/view/AC/job/zosAnsible/1344/console`
CI/CD:
image

**Comment by ddimatos** [comment]
@fernandofloresg , there is no plan to release a 1.4.1 but should we, this `support/v1.4.1` branch is protected and we have it ready to go.

**Comment by fernandofloresg** [comment]
This looks good to me, we have a fix inline for v1.4.1 so merging this now.

**Review by fernandofloresg — APPROVED** [review]

**Pull request merged**
