### PR TITLE
[Enabler] [module_utils/dd_statement.py] Changed try except pass to except specific DatasetDeleteError exception

### LINKED ISSUE #876: [Enabler] Static Scan issue - linked to '#22'
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

_No response_

### Enabler description

[Enabler] Static Scan issue - linked to '#22'

### PR DESCRIPTION
**Pull request by fernandofloresg**
##### SUMMARY

Currently Bandit marks Try, Except, Pass as a warning, since is not a security issue but rather a behavior that might ignore wrong doings.

This change instead catches any data set deletion error and passes, but raises any other potential issue.

Added details of the code to changelog, since is a trivial change it will not be included in the release notes so no final user will see this.

Fixes #876 

##### ISSUE TYPE

- Enhancement Pull Request

##### COMPONENT NAME

module_utils/dd_statement.py used also by zos_mvs_raw.

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by fernandofloresg** [comment]
Screenshot 2023-11-06 at 8 44 42 PM


Screenshot 2023-11-06 at 8 45 01 PM

**Review by richp405 — APPROVED** [review]
Getting rid of an warning by being more specific... good idea!

**Review by rexemin — APPROVED** [review]
Looks good

**Review by ketankelkar — APPROVED** [review]
LGTM, it's really nice to see our exception flows being tightened up

**Pull request merged**
