### PR TITLE
Add test case to validate response come back complete

### LINKED ISSUE #782: [Bug] zos_operator command respones come back truncated
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.2

### IBM Enterprise Python

v3.9.x

### IBM z/OS Ansible core Version

v1.5.0

### ansible-version

v2.14.x

### z/OS version

v2.5

### Ansible module

zos_operator

### Bug description

Issue #644 reported two problems, one was doc related which was resolved, the second issue was about how the module `zos_operator` would truncate command responses. See issue #644 which demonstrates how the `\\$DSPOOL` command came truncated when using `ibm_zos_core` 1.5.0 and yet in ibm_zos_core 1.4.0 it did not. This difference in behavior had been explained in issue #644 where in 1.4.0 the code was owned and maintained by the Ansible team where in 1.5.0 the Ansible team sunset the code and leveraged ZOAU `opercmd` APIs so that the SDSF dependency could be removed. 

After speaking with ZOAU it was determined that the reason for this behavior is that `opercmd` would return as soon as a message was put in the response register, although this is ideal so if one did set a `wait_time_s` of 30 seconds it would return early but the problem is on busy systems, that first buffer insertion may not be the complete message and more is coming, which resulted in a truncated response. 

The solution to this issue comes in ZOAU 1.2.4 and the behavior changes a bit, now the response register is not the only data point, now `opercmd` monitors the register and the timeout and ensures the full time out is satisfied before returning. 

The default is 1 second which should be more than enough for most systems, even though the default was 1 second before, as I noted, once the register had data in it, `opercmd` would return not fulfilling the full 1 second. 

This is mostly a validation item ensuring ZOAU 1.2.4 operates as designed and if applicable a new test case can be added. 

### Playbook verbosity output.

_No response_

### Ansible configuration.

_No response_

### Contents of the inventory

_No response_

### Contents of `group_vars` or `host_vars`

_No response_

### PR DESCRIPTION
**Pull request by AndreMarcel99**
##### SUMMARY
Add test case to validate the solution on of command response is full in the output.

Validate the fix #782 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
Test case test_response_come_back_complete that validates the final line of the response contains HASP646

Required ZOAU 1.2.4
Captura de pantalla 2023-08-02 a la(s) 9 11 45

Captura de pantalla 2023-08-02 a la(s) 9 12 08

Captura de pantalla 2023-08-02 a la(s) 9 12 28

### CODE REVIEW

**Review by richp405 — APPROVED** [review]
Nice solution for dspl command.

**Comment by ketankelkar** [comment]
tested for presence of `$HASP646` in zVM
```
0210  $D SPL                                            
0010  $HASP893 VOLUME(SPOOL1)  STATUS=ACTIVE,PERCENT=1  
0010  $HASP646 0.5965 PERCENT SPOOL UTILIZATION         
```

tested for presence of `$HASP646` on bare metal
```
   Display  Filter  View  Print  Options  Search  Help                          
 -------------------------------------------------------------------------------
 SDSF OPERLOG  STLABB3  08/03/2023     0W                       COLUMNS 52- 131 
 COMMAND INPUT ===>                                            SCROLL ===> PAGE 
     
000210  $D SPOOL                                                                
000010  $HASP893 VOLUME(LABB14)  STATUS=ACTIVE,PERCENT=1                        
000010  $HASP893 VOLUME(LABB10)  STATUS=ACTIVE,PERCENT=6                        
000010  $HASP646 1.9250 PERCENT SPOOL UTILIZATION                               
```

**Review by ketankelkar — COMMENTED** [review]
LGTM, just need a latest pipeline run for approval

**Comment by ketankelkar** [comment]
image

**Review by ketankelkar — APPROVED** [review]
lgtm

**Pull request merged**
