### PR TITLE
zos_copy forward port a test case for symbols on a volume

### LINKED ISSUE #738: [Enabler] Forward port test case for Symbols
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_copy

### Enabler description

Issue #543 was temporarily fixed until ZOAU 1.2.2 was available, this issue its to test that fix in ZOAU and to port forward a test cases from 1.4.1 found in PR #566. The test case to be forward ported is `test_copy_pds_member_with_system_symbol`

This is being forward ported from 1.4.1/1.4.0 with commit `5e6eadeed116161b84946a758e96d20088339a21`

### PR DESCRIPTION
**Pull request by ddimatos**
##### SUMMARY
This adds a test for testing of special chars in a volume. This test cases verifies that zoau 1.2.2 has corrected the behavior hence we only pulled the test case forward from 1.4.0 and not the work around. 

Resolves  #738 

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by ddimatos** [comment]
pipeline `AC/job/zosAnsible/1655/parameters/`
image

**Comment by ddimatos** [comment]
You can see from listcat ent('SYS1.SAMPLIB') all the output has symbols for the volume. 

image

**Review by ketankelkar — COMMENTED** [review]
lgtm, only thing i'd suggest is adding more comments describing that the volume `SYS1.SAMPLIB` resides on is a symbol. It's not apparent based solely on what's included in this file.

**Comment by ddimatos** [comment]
> lgtm, only thing i'd suggest is adding more comments describing that the volume `SYS1.SAMPLIB` resides on is a symbol. It's not apparent based solely on what's included in this file.

Not sure if you saw the comments in the test case and are requesting more above this:
```def test_copy_pds_member_with_system_symbol(ansible_zos_module,):
    """This test is for bug #543 in GitHub. In some versions of ZOAU,
    datasets.listing can't handle system symbols in volume names and
    therefore fails to get details from a dataset.
    """
    hosts = ansible_zos_module
    # The volume for this dataset should use a system symbol.
    # This dataset and member should be available on any z/OS system.
```

**Comment by ddimatos** [comment]
> lgtm, only thing i'd suggest is adding more comments describing that the volume `SYS1.SAMPLIB` resides on is a symbol. It's not apparent based solely on what's included in this file.

I added more context in the test anyhow given the time we have to deliver.

**Review by rexemin — APPROVED** [review]
Looks good to me. Thanks for adding the additional note in the test case.

**Review by ketankelkar — APPROVED** [review]
thanks for adding more details! even though we know the context right now, the next time someone (including one of us) sees this code, it may not be as clear

**Pull request merged**
